//go:build integration

package clickhouse

import (
	"github.com/flanksource/config-db/api"
	v1 "github.com/flanksource/config-db/api/v1"
	dutyContext "github.com/flanksource/duty/context"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("ClickHouse scraper", func() {
	It("returns the 1,000 orders generated by the fixture query", func() {
		Expect(ClickhouseURL).NotTo(BeEmpty())

		configs, err := v1.ParseConfigs("../../fixtures/clickhouse.yaml")
		Expect(err).NotTo(HaveOccurred())
		Expect(configs).To(HaveLen(1))

		results := ClickhouseScraper{}.Scrape(
			api.NewScrapeContext(dutyContext.New()).WithScrapeConfig(&configs[0]),
		)
		Expect(results.Errors()).To(BeEmpty())
		Expect(results).To(HaveLen(1000))
	})
})
