version: 2
groups:
  dependabot:
    patterns:
      - "*"
    exclude-patterns:
      - "flanksource/*"
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/hack/generate-schemas"
    schedule:
      interval: "daily"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
