version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      # Group all updates together into a single PR
      all-dependencies:
        patterns:
          - "*"  # Wildcard matches all dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      # Group all updates together into a single PR
      all-dependencies:
        patterns:
          - "*"  # Wildcard matches all dependencies
