package v1

import (
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/flanksource/clicky"
	"github.com/flanksource/clicky/api"
	"github.com/flanksource/clicky/api/icons"
	"github.com/flanksource/commons/collections/set"
	"github.com/flanksource/commons/logger"
	"github.com/flanksource/duty"
	"github.com/flanksource/duty/models"
	"github.com/flanksource/duty/types"
	"github.com/flanksource/is-healthy/pkg/health"
	"github.com/google/uuid"
	"github.com/ohler55/ojg/jp"
	"github.com/ohler55/ojg/oj"
	"github.com/samber/lo"
	"google.golang.org/protobuf/types/known/structpb"
	"gopkg.in/yaml.v3"
	"k8s.io/apimachinery/pkg/fields"

	"github.com/flanksource/config-db/utils"
)

var ErrRateLimited = errors.New("rate limited")

const maxTagsCount = 5

// Analyzer ...
// +kubebuilder:object:generate=false
type Analyzer func(configs []ScrapeResult) AnalysisResult

var severityRank = map[models.Severity]int{
	models.SeverityCritical: 5,
	models.SeverityHigh:     4,
	models.SeverityMedium:   3,
	models.SeverityLow:      2,
	models.SeverityInfo:     1,
}

// IsMoreSevere compares whether s1 is more severe than s2.
func IsMoreSevere(s1, s2 models.Severity) bool {
	return severityRank[s1] > severityRank[s2]
}

// AnalysisResult ...
// +kubebuilder:object:generate=false
type AnalysisResult struct {
	// Id of the analysis at the external source.
	// Most of the time, it's generated by us in a deterministic manner.
	ExternalAnalysisID string `json:"external_analysis_id,omitempty"`

	ExternalID      string              `json:"external_id,omitempty"`
	ConfigType      string              `json:"config_type,omitempty"`
	Summary         string              `json:"summary,omitempty"`
	Analysis        map[string]any      `json:"analysis,omitempty"`
	Properties      types.Properties    `json:"properties,omitempty"`
	AnalysisType    models.AnalysisType `json:"analysis_type,omitempty"`
	Severity        models.Severity     `json:"severity,omitempty"`
	Source          string              `json:"source,omitempty"`
	Analyzer        string              `json:"analyzer,omitempty"`
	Messages        []string            `json:"messages,omitempty"`
	Status          string              `json:"status,omitempty"`
	FirstObserved   *time.Time          `json:"first_observed,omitempty"`
	LastObserved    *time.Time          `json:"last_observed,omitempty"`
	Error           error               `json:"-"`
	ExternalConfigs []ExternalID        `json:"external_configs,omitempty"`
}

// ToConfigAnalysis converts this analysis result to a config analysis
// db model.
func (t *AnalysisResult) ToConfigAnalysis() models.ConfigAnalysis {
	ca := models.ConfigAnalysis{
		Analyzer:      t.Analyzer,
		Message:       strings.Join(t.Messages, "<br><br>"),
		Severity:      t.Severity,
		AnalysisType:  t.AnalysisType,
		Summary:       t.Summary,
		Analysis:      t.Analysis,
		Status:        t.Status,
		Source:        t.Source,
		FirstObserved: t.FirstObserved,
		LastObserved:  t.LastObserved,
	}
	if len(t.Properties) > 0 {
		props := t.Properties
		ca.Properties = &props
	}
	return ca
}

// +kubebuilder:object:generate=false
type ChangeResult struct {
	// ID of the config this change is for
	ConfigID string `json:"configID,omitempty"`

	// (ExternalID, ConfigType) to identify the config this change is for in absence of ConfigID
	ExternalID string `json:"external_id"`
	ConfigType string `json:"config_type"`

	// Scraper id of the config for external config lookup.
	// If left empty, the scraper id is the requester's scraper id.
	// Use `all` to disregard scraper id (useful when changes come from different scraper).
	ScraperID string `json:"scraper_id"`

	ExternalChangeID string         `json:"external_change_id"`
	Action           ChangeAction   `json:"action"`
	ChangeType       string         `json:"change_type"`
	Patches          string         `json:"patches"`
	Summary          string         `json:"summary"`
	Severity         string         `json:"severity"`
	Source           string         `json:"source"`
	CreatedBy        *string        `json:"created_by"`
	CreatedAt        *time.Time     `json:"created_at"`
	Details          map[string]any `json:"details"`
	Diff             *string        `json:"diff,omitempty"`

	// UpdateExisting indicates whether to update an existing change
	UpdateExisting bool `json:"update_existing"`

	// AncestorType is set by move-up/copy-up change mappings to specify
	// which ancestor config type to target during parent chain traversal.
	AncestorType string `json:"-"`

	// Target is set by copy/move change mappings to specify the config item
	// selector for resolving target config items.
	Target *duty.RelationshipSelectorTemplate `json:"-"`

	// For storing struct as map[string]any
	_map map[string]any `json:"-"`
}

func (r *ChangeResult) AsMap() map[string]any {
	if r._map != nil {
		return r._map
	}
	r._map = map[string]any{
		"external_id":        r.ExternalID,
		"config_type":        r.ConfigType,
		"external_change_id": r.ExternalChangeID,
		"action":             r.Action,
		"change_type":        r.ChangeType,
		"patches":            r.Patches,
		"summary":            r.Summary,
		"severity":           r.Severity,
		"source":             r.Source,
		"created_by":         r.CreatedBy,
		"created_at":         r.CreatedAt,
		"details":            r.Details,
		"diff":               r.Diff,
		"config_id":          r.ConfigID,
		"configID":           r.ConfigID, // config_id should be used, this for backward compatibility
		"update_existing":    r.UpdateExisting,
	}
	return r._map
}

func (r *ChangeResult) FlushMap() {
	r._map = nil
}

func (r ChangeResult) PatchesMap() map[string]any {
	output := make(map[string]any)
	if r.Patches != "" {
		if err := json.Unmarshal([]byte(r.Patches), &output); err != nil {
			logger.Errorf("failed to unmarshal: %v", err)
		}
	}

	return output
}

func (c ChangeResult) String() string {
	if c.ConfigID == "" {
		return fmt.Sprintf("{%s/%s}, {%s/%s}", c.ConfigType, c.ExternalID, c.ChangeType, c.ExternalChangeID)
	}

	return fmt.Sprintf("{%s}, {%s/%s}", c.ConfigID, c.ChangeType, c.ExternalChangeID)
}

func (c ChangeResult) Columns() []api.ColumnDef {
	return []api.ColumnDef{
		clicky.Column("ChangeType").Build(),
		clicky.Column("Summary").Build(),
		clicky.Column("Source").Build(),
		clicky.Column("CreatedBy").Build(),
		clicky.Column("Severity").Build(),
		clicky.Column("CreatedAt").Build(),
	}
}

func (c ChangeResult) Row() map[string]any {
	createdAt := ""
	if c.CreatedAt != nil {
		createdAt = c.CreatedAt.Format(time.RFC3339)
	}
	createdBy := ""
	if c.CreatedBy != nil {
		createdBy = *c.CreatedBy
	}
	return map[string]any{
		"ChangeType": clicky.Text(c.ChangeType),
		"Summary":    clicky.Text(c.Summary),
		"Source":     clicky.Text(c.Source),
		"Severity":   clicky.Text(c.Severity),
		"CreatedAt":  clicky.Text(createdAt),
		"CreatedBy":  clicky.Text(createdBy),
	}
}

func (c ChangeResult) Pretty() api.Text {
	t := clicky.Text("")
	switch c.Action {
	case MoveUp:
		t = t.Add(icons.ArrowUp).Append("move-up", "text-bold text-blue-500")
	case Move:
		t = t.Add(icons.ArrowDown).Append("move-down", "text-bold text-blue-500")
	case CopyUp:
		t = t.Add(icons.Add).Append("copy-up", "text-bold text-green-500")
	case Copy:
		t = t.Add(icons.Add).Append("copy", "text-bold text-green-500")
	case Delete:
		t = t.Add(icons.Delete).Append("delete", "text-bold text-red-500")
	case Ignore:
		t = t.Add(icons.Edit).Append("update", "text-bold text-yellow-500")
	default:
		t = t.Append(string(c.Action), "text-bold")
	}

	// first print details about the config item being changed or referenced
	if c.ConfigType != "" {
		t = t.Append(c.ConfigType).Append("/", "text-muted")
	}
	if c.ConfigID != "" {
		t = t.Append(" config_id: ", "text-muted").Append(c.ConfigID)
	}
	if c.ExternalChangeID != "" {
		t = t.Append(" change_id: ", "text-muted").Append(c.ExternalChangeID)
	}
	if c.ExternalID != "" {
		t = t.Append(" external_id: ", "text-muted").Append(c.ExternalID)
	}

	if len(c.Details) > 0 {
		t = t.Append(" details: ", "text-muted").Append(lo.Keys(c.Details))
	}

	if c.Summary != "" {
		t = t.Append(" summary: ", "text-muted").Append(c.Summary)
	}

	if c.Target != nil && !c.Target.IsEmpty() {
		t = t.Append(" target: ", "text-muted").Append(c.Target)
	}

	return t
}

func (result AnalysisResult) String() string {
	return fmt.Sprintf("%s: %s", result.Analyzer, result.Messages)
}

func (result *AnalysisResult) Message(msg string) *AnalysisResult {
	if msg == "" {
		return result
	}
	result.Messages = append(result.Messages, msg)
	return result
}

// +kubebuilder:object:generate=false
type AnalysisResults []AnalysisResult

// +kubebuilder:object:generate=false
type EntitySummary struct {
	Scraped int `json:"scraped,omitempty"`
	Saved   int `json:"saved,omitempty"`
	Skipped int `json:"skipped,omitempty"`
	Deleted int `json:"deleted,omitempty"`
}

func (e EntitySummary) IsEmpty() bool {
	return e.Scraped == 0 && e.Saved == 0 && e.Skipped == 0 && e.Deleted == 0
}

func (e EntitySummary) Merge(other EntitySummary) EntitySummary {
	return EntitySummary{
		Scraped: e.Scraped + other.Scraped,
		Saved:   e.Saved + other.Saved,
		Skipped: e.Skipped + other.Skipped,
		Deleted: e.Deleted + other.Deleted,
	}
}

func (e EntitySummary) Pretty() api.Text {
	t := clicky.Text("")
	if e.Scraped > 0 {
		t = t.Appendf("%d", e.Scraped).AddText(" scraped", "muted")
	}
	if e.Saved > 0 {
		t = t.Space().Appendf("%d", e.Saved).AddText(" saved", "success")
	}
	if e.Skipped > 0 {
		t = t.Space().Appendf("%d", e.Skipped).AddText(" skipped", "warning")
	}
	if e.Deleted > 0 {
		t = t.Space().Appendf("%d", e.Deleted).AddText(" deleted", "error")
	}
	return t
}

func (e EntitySummary) String() string {
	return e.Pretty().String()
}

// +kubebuilder:object:generate=false
type ScrapeSummary struct {
	ConfigTypes    map[string]ConfigTypeScrapeSummary `json:"config_types,omitempty"`
	ExternalUsers  EntitySummary                      `json:"external_users,omitempty"`
	ExternalGroups EntitySummary                      `json:"external_groups,omitempty"`
	ExternalRoles  EntitySummary                      `json:"external_roles,omitempty"`
	ConfigAccess   EntitySummary                      `json:"config_access,omitempty"`
	AccessLogs     EntitySummary                      `json:"access_logs,omitempty"`
}

func NewScrapeSummary() ScrapeSummary {
	return ScrapeSummary{ConfigTypes: make(map[string]ConfigTypeScrapeSummary)}
}

func (summary ScrapeSummary) HasUpdates() bool {
	totals := summary.Totals()
	if totals.Added > 0 || totals.Updated > 0 || totals.Changes > 0 || totals.Deduped > 0 {
		return true
	}
	return !summary.ExternalUsers.IsEmpty() ||
		!summary.ExternalGroups.IsEmpty() ||
		!summary.ExternalRoles.IsEmpty() ||
		!summary.ConfigAccess.IsEmpty() ||
		!summary.AccessLogs.IsEmpty()
}

func (s *ScrapeSummary) UnmarshalJSON(data []byte) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Detect new-format payloads by checking for any known top-level key
	newFormatKeys := []string{"config_types", "external_users", "external_groups", "external_roles", "config_access", "access_logs"}
	isNewFormat := false
	for _, key := range newFormatKeys {
		if _, ok := raw[key]; ok {
			isNewFormat = true
			break
		}
	}

	if isNewFormat {
		type Alias ScrapeSummary
		var a Alias
		if err := json.Unmarshal(data, &a); err != nil {
			return err
		}
		*s = ScrapeSummary(a)
		return nil
	}

	// Legacy format: treat entire payload as map[string]ConfigTypeScrapeSummary
	var m map[string]ConfigTypeScrapeSummary
	if err := json.Unmarshal(data, &m); err != nil {
		return err
	}
	s.ConfigTypes = m
	return nil
}

func (summary ConfigTypeScrapeSummary) String() string {
	s := []string{}

	if summary.Added > 0 {
		s = append(s, fmt.Sprintf("added=%d", summary.Added))
	}
	if summary.Updated > 0 {
		s = append(s, fmt.Sprintf("updated=%d", summary.Updated))
	}
	if summary.Unchanged > 0 {
		s = append(s, fmt.Sprintf("unchanged=%d", summary.Unchanged))
	}
	if summary.Changes > 0 {
		s = append(s, fmt.Sprintf("changes=%d", summary.Changes))
	}
	if summary.Deduped > 0 {
		s = append(s, fmt.Sprintf("deduped=%d", summary.Deduped))
	}
	for _, w := range summary.Warnings {
		s = append(s, fmt.Sprintf("warning=%s", w))
	}

	if summary.Change != nil && len(summary.Change.Ignored) > 0 {
		s = append(s, fmt.Sprintf("ignored=%d", lo.Sum(lo.Values(summary.Change.Ignored))))
	}
	if summary.Change != nil && len(summary.Change.Orphaned) > 0 {
		total := 0
		for _, orphaned := range summary.Change.Orphaned {
			total += orphanedCount(orphaned)
		}
		s = append(s, fmt.Sprintf("orphaned=%d", total))
	}

	return strings.Join(s, ", ")
}

func (s ScrapeSummary) String() string {
	types := lo.Keys(s.ConfigTypes)
	if len(types) <= 3 {
		return fmt.Sprintf("(%s) %v", types, s.Totals())
	}
	return fmt.Sprintf("types=%d, %v", len(types), s.Totals())
}

func (a ConfigTypeScrapeSummary) Merge(b ConfigTypeScrapeSummary) ConfigTypeScrapeSummary {
	change := &ChangeSummary{}
	if a.Change != nil {
		change.Merge(*a.Change)
	}
	if b.Change != nil {
		change.Merge(*b.Change)
	}
	return ConfigTypeScrapeSummary{
		Added:     a.Added + b.Added,
		Updated:   a.Updated + b.Updated,
		Unchanged: a.Unchanged + b.Unchanged,
		Changes:   a.Changes + b.Changes,
		Deduped:   a.Deduped + b.Deduped,
		Change:    change,
	}
}

func (s ScrapeSummary) Totals() ConfigTypeScrapeSummary {
	merged := ConfigTypeScrapeSummary{
		Change: &ChangeSummary{},
	}

	for _, v := range s.ConfigTypes {
		merged = merged.Merge(v)
	}
	return merged
}

func (t *ScrapeSummary) initConfigTypes() {
	if t.ConfigTypes == nil {
		t.ConfigTypes = make(map[string]ConfigTypeScrapeSummary)
	}
}

func (t *ScrapeSummary) AddChangeSummary(configType string, cs ChangeSummary) {
	t.initConfigTypes()
	v := t.ConfigTypes[configType]
	v.Change = &ChangeSummary{
		Ignored:          cs.Ignored,
		IgnoredByAction:  cs.IgnoredByAction,
		Orphaned:         cs.Orphaned,
		ForeignKeyErrors: cs.ForeignKeyErrors,
	}
	t.ConfigTypes[configType] = v
}

func (t *ScrapeSummary) AddInserted(configType string) {
	t.initConfigTypes()
	v := t.ConfigTypes[configType]
	v.Added++
	t.ConfigTypes[configType] = v
}

func (t *ScrapeSummary) AddUpdated(configType string) {
	t.initConfigTypes()
	v := t.ConfigTypes[configType]
	v.Updated++
	t.ConfigTypes[configType] = v
}

func (t *ScrapeSummary) AddUnchanged(configType string) {
	t.initConfigTypes()
	v := t.ConfigTypes[configType]
	v.Unchanged++
	t.ConfigTypes[configType] = v
}

func (t *ScrapeSummary) AddWarning(configType, warning string) {
	t.initConfigTypes()
	v := t.ConfigTypes[configType]
	v.Warnings = append(v.Warnings, warning)
	t.ConfigTypes[configType] = v
}

func (t *ScrapeSummary) AddChanges(configType string, count int) {
	t.initConfigTypes()
	v := t.ConfigTypes[configType]
	v.Changes += count
	t.ConfigTypes[configType] = v
}

func (t *ScrapeSummary) AddDeduped(configType string, count int) {
	t.initConfigTypes()
	v := t.ConfigTypes[configType]
	v.Deduped += count
	t.ConfigTypes[configType] = v
}

func (s *ScrapeSummary) Merge(other ScrapeSummary) {
	s.initConfigTypes()
	for k, v := range other.ConfigTypes {
		if existing, ok := s.ConfigTypes[k]; ok {
			s.ConfigTypes[k] = existing.Merge(v)
		} else {
			s.ConfigTypes[k] = v
		}
	}
	s.ExternalUsers = s.ExternalUsers.Merge(other.ExternalUsers)
	s.ExternalGroups = s.ExternalGroups.Merge(other.ExternalGroups)
	s.ExternalRoles = s.ExternalRoles.Merge(other.ExternalRoles)
	s.ConfigAccess = s.ConfigAccess.Merge(other.ConfigAccess)
	s.AccessLogs = s.AccessLogs.Merge(other.AccessLogs)
}

// +kubebuilder:object:generate=false
type ChangeSummary struct {
	Orphaned         map[string]OrphanedChanges `json:"orphaned,omitempty"`
	Ignored          map[string]int             `json:"ignored,omitempty"`
	IgnoredByAction  map[string]map[string]int  `json:"ignored_by_action,omitempty"` // action -> change_type -> count
	ForeignKeyErrors int                        `json:"foreign_key_errors,omitempty"`
}

// +kubebuilder:object:generate=false
type OrphanedChanges struct {
	IDs   set.Set[string] `json:"ids,omitempty"`
	Count int             `json:"count,omitempty"`
}

func (t ChangeSummary) IsEmpty() bool {
	return len(t.Orphaned) == 0 && len(t.Ignored) == 0
}

func (t *ChangeSummary) AddOrphaned(typ, id string) {
	if t.Orphaned == nil {
		t.Orphaned = make(map[string]OrphanedChanges)
	}
	orphaned := t.Orphaned[typ]
	orphaned.Count++
	if id != "" {
		if orphaned.IDs == nil {
			orphaned.IDs = set.New[string]()
		}
		orphaned.IDs.Add(id)
	}
	t.Orphaned[typ] = orphaned
}

func (t *ChangeSummary) AddIgnored(typ string) {
	if t.Ignored == nil {
		t.Ignored = make(map[string]int)
	}
	t.Ignored[typ] += 1
}

func (t *ChangeSummary) AddIgnoredByAction(action, changeType string) {
	if t.IgnoredByAction == nil {
		t.IgnoredByAction = make(map[string]map[string]int)
	}
	if t.IgnoredByAction[action] == nil {
		t.IgnoredByAction[action] = make(map[string]int)
	}
	t.IgnoredByAction[action][changeType] += 1
}

func (t *ChangeSummary) Merge(b ChangeSummary) {
	if b.Orphaned != nil {
		if t.Orphaned == nil {
			t.Orphaned = make(map[string]OrphanedChanges)
		}
		for k, v := range b.Orphaned {
			orphaned := t.Orphaned[k]
			orphaned.Count += orphanedCount(v)
			if v.IDs != nil {
				if orphaned.IDs == nil {
					orphaned.IDs = set.New[string]()
				}
				for _, id := range v.IDs.ToSlice() {
					orphaned.IDs.Add(id)
				}
			}
			t.Orphaned[k] = orphaned
		}
	}

	if b.Ignored != nil {
		if t.Ignored == nil {
			t.Ignored = make(map[string]int)
		}
		for k, v := range b.Ignored {
			t.Ignored[k] += v
		}
	}

	if b.IgnoredByAction != nil {
		if t.IgnoredByAction == nil {
			t.IgnoredByAction = make(map[string]map[string]int)
		}
		for action, changeTypes := range b.IgnoredByAction {
			if t.IgnoredByAction[action] == nil {
				t.IgnoredByAction[action] = make(map[string]int)
			}
			for changeType, count := range changeTypes {
				t.IgnoredByAction[action][changeType] += count
			}
		}
	}
}

func (t *ChangeSummary) Totals() (ignored, orphaned, errors int) {
	if t == nil {
		return 0, 0, 0
	}
	for _, v := range t.Ignored {
		ignored += v
	}
	for _, changeTypes := range t.IgnoredByAction {
		for _, count := range changeTypes {
			ignored += count
		}
	}
	for _, v := range t.Orphaned {
		orphaned += orphanedCount(v)
	}
	return ignored, orphaned, t.ForeignKeyErrors
}

func orphanedCount(orphaned OrphanedChanges) int {
	if orphaned.Count > 0 {
		return orphaned.Count
	}
	if orphaned.IDs == nil {
		return 0
	}
	return len(orphaned.IDs.ToSlice())
}

// +kubebuilder:object:generate=false
type ChangeSummaryByType map[string]ChangeSummary

func (t *ChangeSummaryByType) Merge(typ string, b ChangeSummary) {
	v := (*t)[typ]
	v.Merge(b)
	(*t)[typ] = v
}

// +kubebuilder:object:generate=false
type ConfigTypeScrapeSummary struct {
	Added     int            `json:"added,omitempty"`
	Updated   int            `json:"updated,omitempty"`
	Unchanged int            `json:"unchanged,omitempty"`
	Changes   int            `json:"changes,omitempty"`
	Deduped   int            `json:"deduped,omitempty"`
	Change    *ChangeSummary `json:"change,omitempty"`
	Warnings  []string       `json:"warnings,omitempty"`
}

// +kubebuilder:object:generate=false
type ScrapeResults []ScrapeResult

func (t ScrapeResults) HasErr() bool {
	for _, r := range t {
		if r.Error != nil {
			return true
		}
	}

	return false
}

func (t ScrapeResults) Errors() []string {
	var errs []string
	for _, r := range t {
		if r.Error != nil {
			errs = append(errs, r.Error.Error())
		}
	}

	return errs
}

func (t *ScrapeResults) Add(r ...ScrapeResult) {
	*t = append(*t, r...)
}

type RelationshipResult struct {
	// Config ID of the parent
	ConfigID string
	// ConfigExternalID is the external id to lookup the actual config item ID.
	// used when the config id is not known.
	ConfigExternalID ExternalID

	// Related External ID to lookup the actual config item ID.
	// Used when the related config id is not known.
	RelatedExternalID ExternalID
	// Config ID of the related config.
	RelatedConfigID string

	Relationship string
}

// Swap swaps the parent and child
func (t *RelationshipResult) Swap() {
	t.ConfigID, t.RelatedConfigID = t.RelatedConfigID, t.ConfigID
	t.ConfigExternalID, t.RelatedExternalID = t.RelatedExternalID, t.ConfigExternalID
}

func (t RelationshipResult) WithConfig(id string, ext ExternalID) RelationshipResult {
	if id != "" {
		t.ConfigID = id
	} else {
		t.ConfigExternalID = ext
	}
	return t
}

func (t RelationshipResult) WithRelated(id string, ext ExternalID) RelationshipResult {
	if id != "" {
		t.RelatedConfigID = id
	} else {
		t.RelatedExternalID = ext
	}
	return t
}

func (r RelationshipResult) Pretty() api.Text {
	t := clicky.Text("")
	if !r.ConfigExternalID.IsEmpty() {
		t = t.Add(r.ConfigExternalID.Pretty())
	} else if r.ConfigID != "" {
		t = t.Append(r.ConfigID, "text-sm")
	}
	t = t.Append(" → ", "text-muted")
	if !r.RelatedExternalID.IsEmpty() {
		t = t.Add(r.RelatedExternalID.Pretty())
	} else if r.RelatedConfigID != "" {
		t = t.Append(r.RelatedConfigID, "text-sm")
	}
	if r.Relationship != "" {
		t = t.Append(" ("+r.Relationship+")", "text-muted")
	}
	return t
}

func (r RelationshipResults) Pretty() api.Text {
	t := clicky.Text("")
	for i, rel := range r {
		if i > 0 {
			t = t.NewLine()
		}
		t = t.Append("  ").Add(rel.Pretty())
	}
	return t
}

func (r RelationshipResult) String() string {
	s := ""
	if r.ConfigID != "" {
		s += fmt.Sprintf("config_id=%s ", r.ConfigID)
	}
	if !r.ConfigExternalID.IsEmpty() {
		s += fmt.Sprintf("config_external_id=%s ", r.ConfigExternalID)
	}
	if r.RelatedConfigID != "" {
		s += fmt.Sprintf("related_config_id=%s ", r.RelatedConfigID)
	}
	if !r.RelatedExternalID.IsEmpty() {
		s += fmt.Sprintf("related_external_id=%s ", r.RelatedExternalID)
	}
	s += fmt.Sprintf("relationship=%s", r.Relationship)
	return s
}

type RelationshipResults []RelationshipResult

func (s *ScrapeResults) AddChange(base BaseScraper, change ChangeResult) *ScrapeResults {
	*s = append(*s, ScrapeResult{
		BaseScraper: base,
		Changes:     []ChangeResult{change},
	})
	return s
}

func (s *ScrapeResults) Analysis(analyzer string, configType string, id string) *AnalysisResult {
	result := AnalysisResult{
		Analyzer:   analyzer,
		ConfigType: configType,
		ExternalID: id,
	}
	*s = append(*s, ScrapeResult{
		AnalysisResult: &result,
	})
	return &result
}

func (s *ScrapeResults) RateLimited(msg string, resetAt *time.Time) ScrapeResults {
	logger.Warnf("rate limited: %s (reset at %v)", msg, resetAt)
	*s = append(*s, ScrapeResult{
		Error:            fmt.Errorf("%s: %w", msg, ErrRateLimited),
		RateLimitResetAt: resetAt,
	})
	return *s
}

func (t ScrapeResults) IsRateLimited() bool {
	for _, r := range t {
		if errors.Is(r.Error, ErrRateLimited) {
			return true
		}
	}
	return false
}

func (t ScrapeResults) GetRateLimitResetAt() *time.Time {
	for _, r := range t {
		if r.RateLimitResetAt != nil {
			return r.RateLimitResetAt
		}
	}
	return nil
}

func (s *ScrapeResults) Errorf(e error, msg string, args ...any) ScrapeResults {
	errMsg := fmt.Sprintf(msg, args...)
	logger.Errorf("%s: %v", errMsg, e)
	*s = append(*s, ScrapeResult{Error: fmt.Errorf("%s: %w", errMsg, e)})
	return *s
}

type Tag struct {
	Name     string `json:"name"`
	Label    string `json:"label,omitempty"`
	JSONPath string `json:"jsonpath,omitempty"`
	Value    string `json:"value,omitempty"`
}

type Tags []Tag

func (t *Tags) Append(name, value string) {
	if t == nil {
		return
	}

	if value == "" {
		return
	}

	if *t == nil {
		*t = make(Tags, 0, 1)
	}

	*t = append(*t, Tag{Name: name, Value: value})
}

func (t Tags) Has(name string) bool {
	for _, item := range t {
		if item.Name == name {
			return true
		}
	}

	return false
}

func (t Tags) sanitize() Tags {
	for i := range t {
		t[i].Name = strings.TrimSpace(t[i].Name)
		t[i].Label = strings.TrimSpace(t[i].Label)
		t[i].JSONPath = strings.TrimSpace(t[i].JSONPath)
		t[i].Value = strings.TrimSpace(t[i].Value)
	}

	return t
}

func (t Tags) valid() error {
	if len(t) > maxTagsCount {
		return fmt.Errorf("too many tags (%d). only %d allowed", len(t), maxTagsCount)
	}

	seen := make(map[string]struct{})
	for _, tag := range t {
		if tag.Name == "" {
			return fmt.Errorf("tag with an empty name")
		}

		if _, ok := seen[tag.Name]; ok {
			return fmt.Errorf("tag name %s is duplicated", tag.Name)
		}

		if tag.Value == "" && tag.JSONPath == "" && tag.Label == "" {
			return fmt.Errorf("tag %q should specify either value, jsonpath or label", tag.Name)
		}

		seen[tag.Name] = struct{}{}
	}

	return nil
}

func (t Tags) AsMap() map[string]string {
	if len(t) == 0 {
		return nil
	}

	output := make(map[string]string, len(t))
	for i := range t {
		output[t[i].Name] = t[i].Value
	}

	return output
}

func (t Tags) Eval(labels map[string]string, config string) (Tags, error) {
	if len(t) == 0 {
		return nil, nil
	}

	t = t.sanitize()
	if err := t.valid(); err != nil {
		return nil, err
	}

	for _, tag := range t {
		if tag.Value != "" {
			// do nothing
		} else if tag.Label != "" {
			if val, ok := labels[tag.Label]; ok {
				tag.Value = val
			}
		} else if tag.JSONPath != "" {
			if !utils.IsJSONPath(tag.JSONPath) {
				return nil, fmt.Errorf("tag %q has an invalid json path %s", tag.Name, tag.JSONPath)
			}

			if jsonExpr, err := jp.ParseString(tag.JSONPath); err != nil {
				return nil, fmt.Errorf("failed to parse jsonpath: %s: %v", tag.JSONPath, err)
			} else {
				parsedConfig, err := oj.ParseString(config)
				if err != nil {
					return nil, fmt.Errorf("failed to parse config: %w", err)
				}

				if extractedValues := jsonExpr.Get(parsedConfig); len(extractedValues) > 0 {
					tag.Value = fmt.Sprintf("%v", extractedValues[0])
				}
			}
		}
	}

	return t, nil
}

type ConfigExternalKey struct {
	ExternalID string
	Type       string
	ScraperID  string
}

func (k ConfigExternalKey) Pretty() api.Text {
	return clicky.Text(k.Type, "text-muted").Append("/").Append(k.ExternalID)
}

// +kubebuilder:object:generate=false
type ScrapeResultResolved struct {
	Action        string
	Parents       []ResolvedConfigRef
	Relationships []ResolvedRelationshipRef
	Logs          ScrapeResultLogs
}

// +kubebuilder:object:generate=false
type ScrapeResultLogs []logger.BufferedLogEntry

// ResolvedConfigRef tracks a parent lookup result.
// +kubebuilder:object:generate=false
type ResolvedConfigRef struct {
	Query ConfigExternalKey
	// ID is the resolved config item ID, empty if unmatched
	ID   string
	Name string
}

// ResolvedRelationshipRef tracks a relationship lookup result.
// +kubebuilder:object:generate=false
type ResolvedRelationshipRef struct {
	Query       RelationshipResult
	ConfigName  string
	RelatedName string
	Matched     bool
}

func (r ResolvedConfigRef) Pretty() api.Text {
	t := r.Query.Pretty()
	if r.ID != "" {
		t = t.Append(" → ", "text-muted").Append(r.Name)
	} else {
		t = t.Append(" → ", "text-muted").Append("unmatched", "text-red-500")
	}
	return t
}

func (r ResolvedRelationshipRef) Pretty() api.Text {
	t := clicky.Text("")
	if !r.Query.ConfigExternalID.IsEmpty() {
		t = t.Add(r.Query.ConfigExternalID.Pretty())
	} else if r.Query.ConfigID != "" {
		t = t.Append(r.Query.ConfigID, "text-sm")
	}
	if r.ConfigName != "" {
		t = t.Append(" (", "text-muted").Append(r.ConfigName).Append(")", "text-muted")
	}
	t = t.Append(" → ", "text-muted")
	if !r.Query.RelatedExternalID.IsEmpty() {
		t = t.Add(r.Query.RelatedExternalID.Pretty())
	} else if r.Query.RelatedConfigID != "" {
		t = t.Append(r.Query.RelatedConfigID, "text-sm")
	}
	if r.RelatedName != "" {
		t = t.Append(" (", "text-muted").Append(r.RelatedName).Append(")", "text-muted")
	}
	if !r.Matched {
		t = t.Append(" unmatched", "text-red-500")
	}
	return t
}

func (r ScrapeResultResolved) Pretty() api.Text {
	t := clicky.Text("")
	if r.Action != "" {
		t = t.Append(r.Action, "badge")
	}
	if len(r.Parents) > 0 {
		t = t.NewLine().Append("Parents: ", "text-gray-500 font-medium")
		for _, p := range r.Parents {
			t = t.NewLine().Append("  ").Add(p.Pretty())
		}
	}
	if len(r.Relationships) > 0 {
		t = t.NewLine().Append("Relationships: ", "text-gray-500 font-medium")
		for _, rel := range r.Relationships {
			t = t.NewLine().Append("  ").Add(rel.Pretty())
		}
	}
	if len(r.Logs) > 0 {
		t = t.NewLine().Add(r.Logs.Pretty())
	}
	return t
}

func (l ScrapeResultLogs) Pretty() api.Text {
	t := clicky.Text("Logs: ", "text-gray-500 font-medium")
	var lines []string
	for _, entry := range l {
		lines = append(lines, fmt.Sprintf("[%s] %s", entry.Level, entry.Message))
	}
	t = t.NewLine().Append(clicky.CodeBlock("", strings.Join(lines, "\n")))
	return t
}

type DirectedRelationship struct {
	Selector duty.RelationshipSelector
	Parent   bool
}

// ScrapeResult ...
// +kubebuilder:object:generate=false
type ScrapeResult struct {
	types.NoOpResourceSelectable `json:"-"`

	// ID is the id of the config at it's origin (i.e. the external id)
	// Eg: For Azure, it's the azure resource id and for kuberetenes it's the object UID.
	// If it's a valid UUID & ConfigID is nil, it'll be used as the primary key id of the config item in the database.
	ID string `json:"id,omitempty"`

	// Config ID is the globally unique and persistent uuid of config item,
	// if no suitable ID exists, then it will be generated.
	ConfigID *string `json:"-"`

	CreatedAt           *time.Time          `json:"created_at,omitempty"`
	DeletedAt           *time.Time          `json:"deleted_at,omitempty"`
	DeleteReason        ConfigDeleteReason  `json:"delete_reason,omitempty"`
	LastModified        time.Time           `json:"last_modified,omitempty"`
	ConfigClass         string              `json:"config_class,omitempty"`
	Type                string              `json:"config_type,omitempty"`
	Status              string              `json:"status,omitempty"` // status extracted from the config itself
	Health              models.Health       `json:"health,omitempty"`
	Ready               bool                `json:"ready,omitempty"`
	Name                string              `json:"name,omitempty"`
	Description         string              `json:"description,omitempty"`
	Aliases             []string            `json:"aliases,omitempty"`
	Source              string              `json:"source,omitempty"`
	Config              any                 `json:"config,omitempty"`
	Locations           []string            `json:"locations,omitempty"`
	Format              string              `json:"format,omitempty"`
	Icon                string              `json:"icon,omitempty"`
	Labels              JSONStringMap       `json:"labels,omitempty"`
	Tags                JSONStringMap       `json:"tags,omitempty"`
	BaseScraper         BaseScraper         `json:"-"`
	Error               error               `json:"-"`
	AnalysisResult      *AnalysisResult     `json:"analysis,omitempty"`
	Changes             []ChangeResult      `json:"-"`
	RelationshipResults RelationshipResults `json:"-"`
	Ignore              []string            `json:"-"`
	Action              string              `json:",omitempty"`
	Properties          types.Properties    `json:"properties,omitempty"`

	// ScraperLess when true indicates that this config item
	// does not belong to any scraper. Example: AWS region & availability zone.
	ScraperLess bool `json:"scraper_less,omitempty"`

	// List of candidate parents in order of precision.
	Parents []ConfigExternalKey `json:"-"`

	// List of children whose hard parent should be set to this config item.
	Children []ConfigExternalKey `json:"-"`

	// RelationshipSelectors are used to form relationship of this scraped item with other items.
	// Unlike `RelationshipResults`, selectors give you the flexibility to form relationship without
	// knowing the external ids of the item to be linked.
	RelationshipSelectors []DirectedRelationship `json:"-"`

	ExternalRoles      []models.ExternalRole      `json:"-"`
	ExternalUsers      []models.ExternalUser      `json:"-"`
	ExternalGroups     []models.ExternalGroup     `json:"-"`
	ExternalUserGroups []models.ExternalUserGroup `json:"-"`
	ConfigAccess       []ExternalConfigAccess     `json:"-"`
	ConfigAccessLogs   []ExternalConfigAccessLog  `json:"-"`

	RateLimitResetAt *time.Time `json:"-"`

	// For storing struct as map[string]any
	_map map[string]any `json:"-"`

	// OmitNilFields lets post-processor know whether to omit nil fields
	// inside config or not. Default is true
	OmitNilFields *bool `json:"-"`

	// Only for GCP Scraper
	GCPStructPB *structpb.Struct `json:"-"`

	// Resolved is populated by the save pipeline with resolved parents,
	// relationships, action status, and per-result logs.
	Resolved *ScrapeResultResolved `json:"-"`
}

func (s ScrapeResult) Debug() api.Text {
	t := clicky.Text("")

	t = t.Append("ID: ", "text-muted").Append(s.ID)
	t = t.Append(" Name: ", "text-muted").Append(s.Name)
	t = t.Append(" Type: ", "text-muted").Append(s.Type)
	t = t.Append(" Status: ", "text-muted").Append(s.Status)
	if s.Health != "" && s.Health != models.HealthUnknown {
		t = t.Append(" Health: ", "text-muted").Append(string(s.Health))
	}
	if s.Source != "" {
		t = t.NewLine().Append("Source: ", "text-muted").Append(s.Source)
	}
	if s.ScraperLess {
		t = t.NewLine().Append("Scraper Less: ", "text-muted").Append("true")
	}
	if s.Icon != "" {
		t = t.NewLine().Append("Icon: ", "text-muted").Append(s.Icon)
	}

	if s.Error != nil {
		t = t.Append(" Error: ", "text-red-500").Append(s.Error.Error())
	}
	if len(s.Aliases) > 0 {
		t = t.Append(" Aliases: ", "text-muted").Append(strings.Join(s.Aliases, ", "))
	}
	if s.Description != "" {
		t = t.NewLine().Append("Description: ", "text-muted").Append(s.Description)
	}

	if len(s.Locations) > 0 {
		t = t.NewLine().Append("Locations: ", "text-muted").Append(strings.Join(s.Locations, ", "))
	}

	if len(s.Labels) > 0 {
		t = t.NewLine().Append("Labels: ", "text-muted").Append(clicky.Map(s.Labels))
	}
	if len(s.Tags) > 0 {
		t = t.NewLine().Append("Tags: ", "text-muted").Append(clicky.Map(s.Tags))
	}
	if len(s.Properties) > 0 {
		t = t.NewLine().Append("Properties: ", "text-muted").Append(clicky.Map(s.Properties.AsMap()))
	}

	if len(s.Changes) > 0 {
		t = t.NewLine().Append("Changes: ", "text-muted")
		for _, change := range s.Changes {
			t = t.NewLine().Append(fmt.Sprintf(" - %s: %s", change.ChangeType, change.Summary))
			if len(change.Details) > 0 {
				t = t.NewLine().Append(clicky.Map(change.Details, "max-w-[100ch]")).NewLine()
			}
		}
	}

	switch v := s.Config.(type) {
	case string:
		if s.Format == "json" || s.Format == "" {
			t = t.NewLine().Append(clicky.CodeBlock("json", v)).NewLine()
		} else {
			t = t.NewLine().Append(clicky.CodeBlock(s.Format, v)).NewLine()
		}
	case map[string]any:
		t = t.NewLine().Append(clicky.Map(v), "max-w-[100ch]").NewLine()
	case map[string]string:
		t = t.NewLine().Append(clicky.Map(v), "max-w-[100ch]").NewLine()
	default:
		t = t.NewLine().Append(fmt.Sprintf("%v", v)).NewLine()
	}

	return t
}

func (s ScrapeResult) Columns() []api.ColumnDef {
	return []api.ColumnDef{
		clicky.Column("Name").Build(),
		clicky.Column("Type").Build(),
		clicky.Column("Health").Build(),
		clicky.Column("Error").Build(),
	}
}

func (s ScrapeResult) Row() map[string]any {
	name := s.Name
	if name == "" {
		name = s.ID
	}

	healthStyle := "text-gray-400"
	switch s.Health {
	case "healthy":
		healthStyle = "text-green-600"
	case "unhealthy":
		healthStyle = "text-red-600"
	case "warning":
		healthStyle = "text-yellow-600"
	}

	errText := ""
	if s.Error != nil {
		errText = s.Error.Error()
		if len(errText) > 100 {
			errText = errText[:100] + "…"
		}
	}

	return map[string]any{
		"Name":   clicky.Text(name),
		"Type":   clicky.Text(s.Type, "text-gray-500"),
		"Health": clicky.Text(string(s.Health), healthStyle),
		"Error":  clicky.Text(errText, "text-red-500 text-xs"),
	}
}

func (s ScrapeResult) RowDetail() api.Textable {
	return buildDetails(s)
}

func (s *ScrapeResult) Pretty() api.Text {
	if s == nil {
		return clicky.Text("nil")
	}
	t := clicky.Text("")
	if s.ConfigClass != "" {
		t = t.Append(s.ConfigClass+"/", "text-muted")
	}
	if s.Name != "" {
		t = t.Append(s.Name)
	}

	if len(s.Changes) > 0 {
		t = t.Append(" changes=", "text-muted").Append(len(s.Changes))
	}
	if len(s.RelationshipResults) > 0 {
		t = t.Append(" relationships=", "text-muted").Append(len(s.RelationshipResults))
	}
	if len(s.Parents) > 0 {
		t = t.Append(" parents=", "text-muted").Append(len(s.Parents))
	}
	if len(s.Children) > 0 {
		t = t.Append(" children=", "text-muted").Append(len(s.Children))
	}
	if len(s.RelationshipSelectors) > 0 {
		t = t.Append(" relations=", "text-muted").Append(len(s.RelationshipSelectors))
	}
	if len(s.ConfigAccess) > 0 {
		t = t.Append(" access=", "text-muted").Append(len(s.ConfigAccess))
	}
	if len(s.ConfigAccessLogs) > 0 {
		t = t.Append(" accessLogs=", "text-muted").Append(len(s.ConfigAccessLogs))
	}
	if len(s.ExternalRoles) > 0 {
		t = t.Append(" roles=", "text-muted").Append(len(s.ExternalRoles))
	}
	if len(s.ExternalUsers) > 0 {
		t = t.Append(" users=", "text-muted").Append(len(s.ExternalUsers))
	}
	if len(s.ExternalGroups) > 0 {
		t = t.Append(" groups=", "text-muted").Append(len(s.ExternalGroups))
	}
	if len(s.ExternalUserGroups) > 0 {
		t = t.Append(" userGroups=", "text-muted").Append(len(s.ExternalUserGroups))
	}
	if len(s.Properties) > 0 {
		t = t.Append(" properties=", "text-muted").Append(len(s.Properties))
	}

	return t
}

// matchingRelationships returns relationships that were resolved from the given selector.
func (s ScrapeResult) matchingRelationships(dr DirectedRelationship) RelationshipResults {
	var matches RelationshipResults
	for _, r := range s.RelationshipResults {
		if dr.Parent {
			if r.RelatedExternalID.ExternalID == s.ID && r.RelatedExternalID.ConfigType == s.Type {
				matches = append(matches, r)
			}
		} else {
			if r.ConfigExternalID.ExternalID == s.ID && r.ConfigExternalID.ConfigType == s.Type {
				matches = append(matches, r)
			}
		}
	}
	return matches
}

func buildDetails(s ScrapeResult) api.Text {
	t := clicky.Text("")
	if s.ID != "" {
		t = t.Append("ID: ", "text-gray-500 font-medium").Append(s.ID)
	}
	if len(s.Aliases) > 0 {
		t = t.NewLine().Append("Aliases: ", "text-gray-500 font-medium").Append(strings.Join(s.Aliases, ", "))
	}
	if len(s.Locations) > 0 {
		t = t.NewLine().Append("Locations: ", "text-gray-500 font-medium").Append(strings.Join(s.Locations, ", "))
	}
	if s.Description != "" {
		t = t.NewLine().Append("Description: ", "text-gray-500 font-medium").Append(s.Description)
	}
	if s.Source != "" {
		t = t.NewLine().Append("Source: ", "text-gray-500 font-medium").Append(s.Source)
	}
	if s.Error != nil {
		t = t.NewLine().Append("Error: ", "text-red-500 font-medium").Append(s.Error.Error())
	}
	if len(s.Labels) > 0 {
		t = t.NewLine().Append("Labels: ", "text-gray-500 font-medium").Append(clicky.Map(s.Labels, "badge"))
	}
	if len(s.Tags) > 0 {
		t = t.NewLine().Append("Tags: ", "text-gray-500 font-medium").Append(clicky.Map(s.Tags, "badge"))
	}
	if s.Resolved != nil {
		t = t.NewLine().Add(s.Resolved.Pretty())
	} else {

		if len(s.Children) > 0 {
			t = t.NewLine().Append("Children: ", "text-gray-500 font-medium")
			for _, c := range s.Children {
				t = t.Add(c.Pretty()).Append(" ", "")
			}
		}
		if len(s.RelationshipResults) > 0 && len(s.RelationshipSelectors) == 0 {
			t = t.NewLine().Append("Relationships: ", "text-gray-500 font-medium")
			t = t.NewLine().Add(s.RelationshipResults.Pretty())
		}
	}
	if len(s.RelationshipSelectors) > 0 {
		t = t.NewLine().Append("Relationship Selectors: ", "text-gray-500 font-medium")
		for _, rs := range s.RelationshipSelectors {
			sel := rs.Selector
			parts := []string{}
			if sel.Type != "" {
				parts = append(parts, "type="+sel.Type)
			}
			if sel.Name != "" {
				parts = append(parts, "name="+sel.Name)
			}
			if sel.ExternalID != "" {
				parts = append(parts, "externalID="+sel.ExternalID)
			}
			if len(sel.Labels) > 0 {
				parts = append(parts, fmt.Sprintf("labels=%v", sel.Labels))
			}
			dir := "related"
			if rs.Parent {
				dir = "parent"
			}
			t = t.NewLine().Append(fmt.Sprintf("  [%s] %s", dir, strings.Join(parts, ", ")), "text-sm")
			matches := s.matchingRelationships(rs)
			if len(matches) > 0 {
				for _, r := range matches {
					t = t.NewLine().Append("    → ").Add(r.Pretty())
				}
			} else {
				t = t.NewLine().Append("    → ", "").Append("(no matches)", "text-muted")
			}
		}
	}
	if len(s.Changes) > 0 {
		changesTable := api.NewTableFrom(s.Changes)
		t = t.NewLine().Append(clicky.Collapsed(fmt.Sprintf("Changes (%d)", len(s.Changes)), &changesTable))
	}
	if s.Config != nil {
		var data any
		switch v := s.Config.(type) {
		case string:
			if json.Unmarshal([]byte(v), &data) != nil {
				data = v
			}
		default:
			data = v
		}
		yamlBytes, err := yaml.Marshal(data)
		if err != nil {
			yamlBytes = []byte(fmt.Sprintf("%v", s.Config))
		}
		t = t.NewLine().Append(clicky.Collapsed("Config", clicky.CodeBlock("yaml", string(yamlBytes))))
	}
	return t
}

// CountsGrid renders scrape result counts as a 2-column grid.
// +kubebuilder:object:generate=false
type CountsGrid []countEntry

type countEntry struct {
	label string
	count int
}

func (g CountsGrid) HTML() string {
	var b strings.Builder
	b.WriteString(`<div class="grid grid-cols-2 gap-x-8 gap-y-2">`)
	for _, e := range g {
		fmt.Fprintf(&b,
			`<div class="flex justify-between px-3 py-1 bg-gray-50 rounded">`+
				`<span class="text-sm font-medium text-gray-500">%s</span>`+
				`<span class="text-sm text-gray-900">%d</span>`+
				`</div>`, e.label, e.count)
	}
	b.WriteString(`</div>`)
	return b.String()
}

func (g CountsGrid) String() string {
	var parts []string
	for _, e := range g {
		parts = append(parts, fmt.Sprintf("%s: %d", e.label, e.count))
	}
	return strings.Join(parts, ", ")
}

func (g CountsGrid) ANSI() string     { return g.String() }
func (g CountsGrid) Markdown() string { return g.String() }

// BuildCounts returns scrape result counts as a 2-column grid.
func BuildCounts(all FullScrapeResults) CountsGrid {
	return CountsGrid{
		{"Configs", len(all.Configs)},
		{"Analysis", len(all.Analysis)},
		{"Changes", len(all.Changes)},
		{"Relationships", len(all.Relationships)},
		{"External Roles", len(all.ExternalRoles)},
		{"External Users", len(all.ExternalUsers)},
		{"External Groups", len(all.ExternalGroups)},
		{"External User Groups", len(all.ExternalUserGroups)},
		{"Config Access", len(all.ConfigAccess)},
		{"Config Access Logs", len(all.ConfigAccessLogs)},
	}
}

var ansiEscapeRegex = regexp.MustCompile(`\x1b\[[0-9;]*m`)

var logLevelRegex = regexp.MustCompile(`\s(INF|ERR|WRN|DBG\S*|TRC\S*|FTL)\s`)

var logLevelStyles = map[string]string{
	"INF": "text-green-600",
	"ERR": "text-red-600",
	"WRN": "text-yellow-600",
	"DBG": "text-blue-600",
	"TRC": "text-gray-500",
	"FTL": "text-red-600 font-bold",
}

// LogOutput renders log lines with colored level prefixes.
// +kubebuilder:object:generate=false
type LogOutput struct {
	lines []string
}

func (l LogOutput) Pretty() api.Text {
	if len(l.lines) == 0 {
		return clicky.Text("")
	}
	t := colorLogLine(l.lines[0])
	for _, line := range l.lines[1:] {
		t = t.NewLine().Append(colorLogLine(line))
	}
	return t
}

func colorLogLine(line string) api.Text {
	loc := logLevelRegex.FindStringIndex(line)
	if loc == nil {
		return clicky.Text(line)
	}
	tag := strings.TrimSpace(line[loc[0]:loc[1]])
	base := tag
	if i := strings.IndexByte(tag, '-'); i >= 0 {
		base = tag[:i]
	}
	return clicky.Text(line[:loc[0]+1]).
		Append(tag, logLevelStyles[base]).
		Append(line[loc[1]-1:])
}

func BuildLogOutput(rawLogs string) LogOutput {
	cleaned := ansiEscapeRegex.ReplaceAllString(rawLogs, "")
	trimmed := strings.TrimRight(cleaned, "\n")
	if trimmed == "" {
		return LogOutput{}
	}
	return LogOutput{lines: strings.Split(trimmed, "\n")}
}

func (s ScrapeResult) IsMetadataOnly() bool {
	return s.Config == nil
}

// +kubebuilder:object:generate=false
type ExternalConfigAccessLog struct {
	models.ConfigAccessLog
	ConfigExternalID    ExternalID `json:"external_config_id,omitempty"`
	ExternalUserAliases []string   `json:"external_user_aliases,omitempty"`
}

func (e ExternalConfigAccessLog) String() string {
	return e.Pretty().String()
}

func (e ExternalConfigAccessLog) Pretty() api.Text {
	t := clicky.Text("").Add(e.ConfigExternalID.Pretty())
	if len(e.ExternalUserAliases) > 0 {
		t = t.Append(" user_aliases=", "text-muted").Append(strings.Join(e.ExternalUserAliases, ","))
	}
	if e.ExternalUserID != uuid.Nil {
		t = t.Append(" user_id=", "text-muted").Append(e.ExternalUserID.String())
	}

	return t
}

func (e ExternalConfigAccessLog) Columns() []api.ColumnDef {
	return []api.ColumnDef{
		clicky.Column("ConfigID").Build(),
		clicky.Column("UserID").Build(),
		clicky.Column("MFA").Build(),
		clicky.Column("Count").Build(),
		clicky.Column("CreatedAt").Type("date").Build(),
	}
}

func (e ExternalConfigAccessLog) Row() map[string]any {
	row := map[string]any{
		"MFA":       e.MFA,
		"CreatedAt": e.CreatedAt,
	}
	if e.ConfigID != uuid.Nil {
		row["ConfigID"] = clicky.Text(e.ConfigID.String())
	} else {
		row["ConfigID"] = e.ConfigExternalID
	}
	if e.Count != nil {
		row["Count"] = *e.Count
	}

	aliases := strings.Join(e.ExternalUserAliases, ",")
	if e.ExternalUserID != uuid.Nil {
		if aliases != "" {
			aliases += ", "
		}
		aliases += e.ExternalUserID.String()
	}
	row["UserID"] = aliases

	return row
}

// +kubebuilder:object:generate=false
type ExternalConfigAccess struct {
	ID            string     `json:"id"`
	ApplicationID *uuid.UUID `json:"application_id,omitempty"`
	ScraperID     *uuid.UUID `json:"scraper_id,omitempty"`
	Source        *string    `json:"source,omitempty"`

	ConfigID        uuid.UUID  `json:"config_id,omitempty"`
	ExternalUserID  *uuid.UUID `json:"external_user_id,omitempty"`
	ExternalGroupID *uuid.UUID `json:"external_group_id,omitempty"`
	ExternalRoleID  *uuid.UUID `json:"external_role_id,omitempty"`

	CreatedAt time.Time  `json:"created_at,omitempty"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	DeletedBy *uuid.UUID `json:"deleted_by,omitempty"`
	CreatedBy *uuid.UUID `json:"created_by,omitempty"`

	LastReviewedAt *time.Time `json:"last_reviewed_at,omitempty"`
	LastReviewedBy *uuid.UUID `json:"last_reviewed_by,omitempty"`

	ConfigExternalID     ExternalID `json:"external_config_id"`
	ExternalUserAliases  []string   `json:"external_user_aliases"`
	ExternalRoleAliases  []string   `json:"external_role_aliases"`
	ExternalGroupAliases []string   `json:"external_group_aliases"`
}

func (e ExternalConfigAccess) HasPrincipal() bool {
	return e.ExternalUserID != nil || e.ExternalGroupID != nil || e.ExternalRoleID != nil ||
		len(e.ExternalUserAliases) > 0 || len(e.ExternalGroupAliases) > 0 || len(e.ExternalRoleAliases) > 0
}

func (e ExternalConfigAccess) ToConfigAccess() models.ConfigAccess {
	return models.ConfigAccess{
		ID:              e.ID,
		ApplicationID:   e.ApplicationID,
		ScraperID:       e.ScraperID,
		Source:          e.Source,
		ConfigID:        e.ConfigID,
		ExternalUserID:  e.ExternalUserID,
		ExternalGroupID: e.ExternalGroupID,
		ExternalRoleID:  e.ExternalRoleID,
		CreatedAt:       e.CreatedAt,
		DeletedAt:       e.DeletedAt,
		DeletedBy:       e.DeletedBy,
		CreatedBy:       e.CreatedBy,
		LastReviewedAt:  e.LastReviewedAt,
		LastReviewedBy:  e.LastReviewedBy,
	}
}

func (e *ExternalConfigAccess) UnmarshalJSON(data []byte) error {
	type Alias ExternalConfigAccess
	aux := &struct {
		ScraperID     *string `json:"scraper_id,omitempty"`
		ApplicationID *string `json:"application_id,omitempty"`
		*Alias
	}{
		Alias: (*Alias)(e),
	}

	if err := json.Unmarshal(data, aux); err != nil {
		return err
	}

	if aux.ScraperID != nil {
		if id, err := uuid.Parse(*aux.ScraperID); err == nil {
			e.ScraperID = &id
		}
	}
	if aux.ApplicationID != nil {
		if id, err := uuid.Parse(*aux.ApplicationID); err == nil {
			e.ApplicationID = &id
		}
	}
	return nil
}

var _ types.ResourceSelectable = (*ScrapeResult)(nil)

func (e ScrapeResult) GetFieldsMatcher() fields.Fields {
	return types.GenericFieldMatcher{Fields: e.AsMap()}
}

func (s ScrapeResult) GetID() string {
	return s.ID
}

func (s ScrapeResult) GetName() string {
	return s.Name
}

func (s ScrapeResult) GetType() string {
	return s.Type
}

func (s ScrapeResult) OmitNil() bool {
	// If unset, always omit nil
	if s.OmitNilFields == nil {
		return true
	}
	return lo.FromPtr(s.OmitNilFields)
}

// SetHealthIfEmpty sets the health, status & readiness of the scrape result
// based on the config type.
func (s ScrapeResult) SetHealthIfEmpty() ScrapeResult {
	if s.Status == "" && s.Health == "" {
		s = s.WithHealthStatus(health.GetHealthByConfigType(s.Type, s.ConfigMap()))
		return s
	}

	if s.Health == "" {
		s.Health = models.HealthUnknown
	}

	return s
}

func (s ScrapeResult) WithHealthStatus(hs health.HealthStatus) ScrapeResult {
	s.Ready = hs.Ready

	if hs.Health != "" {
		s.Health = models.Health(hs.Health)
	}

	if hs.Status != "" {
		s.Status = string(hs.Status)
	}

	if hs.Message != "" {
		s.Description = hs.Message
	}

	return s
}

func (s *ScrapeResult) AsMap() map[string]any {
	if s._map != nil {
		return s._map
	}
	s._map = map[string]any{
		"id":            s.ID,
		"created_at":    s.CreatedAt,
		"deleted_at":    s.DeletedAt,
		"delete_reason": s.DeleteReason,
		"last_modified": s.LastModified,
		"config_class":  s.ConfigClass,
		"config_type":   s.Type,
		"status":        s.Status,
		"health":        s.Health,
		"ready":         s.Ready,
		"name":          s.Name,
		"description":   s.Description,
		"aliases":       s.Aliases,
		"source":        s.Source,
		"config":        s.Config, // TODO Change
		"format":        s.Format,
		"icon":          s.Icon,
		"labels":        s.Labels,
		"tags":          s.Tags,
		"action":        s.Action,
		"properties":    s.Properties.AsMap(),
		"scraper_less":  s.ScraperLess,
	}
	return s._map
}

func NewScrapeResult(base BaseScraper) *ScrapeResult {
	return &ScrapeResult{
		BaseScraper: base,
		Format:      base.Format,
		Tags:        base.Tags.AsMap(),
		Labels:      base.Labels,
	}
}

func (s ScrapeResult) Success(config interface{}) ScrapeResult {
	s.Config = config
	return s
}

func (s ScrapeResult) Errorf(msg string, args ...interface{}) ScrapeResult {
	s.Error = fmt.Errorf(msg, args...)
	return s
}

func (s ScrapeResult) SetError(err error) ScrapeResult {
	s.Error = err
	return s
}

func (s ScrapeResult) Clone(config interface{}) ScrapeResult {
	clone := ScrapeResult{
		LastModified: s.LastModified,
		Aliases:      s.Aliases,
		ConfigClass:  s.ConfigClass,
		Name:         s.Name,
		ID:           s.ID,
		Source:       s.Source,
		Config:       config,
		Labels:       s.Labels,
		Tags:         s.Tags,
		BaseScraper:  s.BaseScraper,
		Format:       s.Format,
		Error:        s.Error,
	}
	return clone
}

// +kubebuilder:object:generate=false
type FullScrapeResults struct {
	Configs            []ScrapeResult              `json:"configs,omitempty"`
	Analysis           []models.ConfigAnalysis     `json:"analysis,omitempty"`
	Changes            []models.ConfigChange       `json:"changes,omitempty"`
	Relationships      []models.ConfigRelationship `json:"relationships,omitempty"`
	ExternalRoles      []models.ExternalRole       `json:"external_roles,omitempty"`
	ExternalUsers      []models.ExternalUser       `json:"external_users,omitempty"`
	ExternalGroups     []models.ExternalGroup      `json:"external_groups,omitempty"`
	ExternalUserGroups []models.ExternalUserGroup  `json:"external_user_groups,omitempty"`
	ConfigAccess       []ExternalConfigAccess      `json:"config_access,omitempty"`
	ConfigAccessLogs   []ExternalConfigAccessLog   `json:"config_access_logs,omitempty"`
}

func MergeScrapeResults(results ...ScrapeResults) FullScrapeResults {
	full := FullScrapeResults{}
	for _, res := range results {
		for _, r := range res {
			if r.Error != nil {
				continue
			}

			if r.AnalysisResult != nil {
				full.Analysis = append(full.Analysis, r.AnalysisResult.ToConfigAnalysis())
			}

			for _, change := range r.Changes {
				configChange := models.ConfigChange{
					ChangeType:        change.ChangeType,
					Severity:          models.Severity(change.Severity),
					Source:            change.Source,
					Summary:           change.Summary,
					CreatedAt:         change.CreatedAt,
					ExternalChangeID:  lo.ToPtr(change.ExternalChangeID),
					ExternalID:        change.ExternalID,
					ConfigType:        change.ConfigType,
					Diff:              lo.FromPtr(change.Diff),
					Patches:           change.Patches,
					ExternalCreatedBy: change.CreatedBy,
				}
				if change.Details != nil {
					if detailsJSON, err := json.Marshal(change.Details); err == nil {
						configChange.Details = detailsJSON
					}
				}
				full.Changes = append(full.Changes, configChange)
			}

			for _, rel := range r.RelationshipResults {
				full.Relationships = append(full.Relationships, models.ConfigRelationship{
					ConfigID:  rel.ConfigID,
					RelatedID: rel.RelatedConfigID,
					Relation:  rel.Relationship,
				})
			}

			if !r.IsMetadataOnly() {
				full.Configs = append(full.Configs, r)
			}

			full.ExternalRoles = append(full.ExternalRoles, r.ExternalRoles...)
			full.ExternalUsers = append(full.ExternalUsers, r.ExternalUsers...)
			full.ExternalGroups = append(full.ExternalGroups, r.ExternalGroups...)
			full.ExternalUserGroups = append(full.ExternalUserGroups, r.ExternalUserGroups...)
			full.ConfigAccess = append(full.ConfigAccess, r.ConfigAccess...)
			full.ConfigAccessLogs = append(full.ConfigAccessLogs, r.ConfigAccessLogs...)
		}
	}
	return full
}

func Ellipses(str string, length int) string {
	if len(str) > length {
		if len(str) < 3 || length < 3 {
			return str
		}
		return str[0:length/2] + "..." + str[len(str)-length/2-3:]
	}
	return str
}

func (r ScrapeResult) String() string {
	s := fmt.Sprintf("%s/%s (%s)", r.ConfigClass, Ellipses(r.Name, 40), Ellipses(r.ID, 40))

	if r.Health != models.HealthUnknown {
		s += fmt.Sprintf(" %s", r.Health)
	}

	if r.Status != "" {
		s += fmt.Sprintf(" %s", Ellipses(r.Status, 20))
	}

	if len(r.Changes) > 0 {
		s += fmt.Sprintf(" changes=%d", len(r.Changes))
	}
	if len(r.RelationshipResults) > 0 {
		s += fmt.Sprintf(" relationships=%d", len(r.RelationshipResults))
	}
	if r.AnalysisResult != nil {
		s += " analysis=1"
	}
	return s
}

// ConfigMap returns the underlying config as a map
func (r ScrapeResult) ConfigString() string {

	// If config is of type string, try unmarshal first
	if v, ok := r.Config.(string); ok {
		return v
	}

	// Marshal and unmarshal into json for other types
	b, err := json.Marshal(r.Config)
	if err != nil {
		logger.Errorf("failed to marshal config: %v", err)
		return ""
	}

	return string(b)
}

// ConfigMap returns the underlying config as a map
func (r ScrapeResult) ConfigMap() map[string]any {
	output := make(map[string]any)

	// If config is of type string, try unmarshal first
	if _, ok := r.Config.(string); ok {
		if err := json.Unmarshal([]byte(r.Config.(string)), &output); err != nil {
			logger.Errorf("failed to unmarshal config: %v", err)
		}
		return output
	}

	// Marshal and unmarshal into json for other types
	b, err := json.Marshal(r.Config)
	if err != nil {
		logger.Errorf("failed to marshal config: %v", err)
		return output
	}

	if err := json.Unmarshal(b, &output); err != nil {
		logger.Errorf("failed to unmarshal config: %v", err)
		return output
	}

	return output
}

// QueryColumn ...
type QueryColumn struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// QueryResult ...
// +kubebuilder:object:generate=false
type QueryResult struct {
	Count   int                      `json:"count"`
	Columns []QueryColumn            `json:"columns"`
	Results []map[string]interface{} `json:"results"`
}

// QueryRequest ...
type QueryRequest struct {
	Query string `json:"query"`
}

// RunNowResponse represents the response body for a run now request
type RunNowResponse struct {
	Total   int      `json:"total"`
	Success int      `json:"success"`
	Failed  int      `json:"failed"`
	Errors  []string `json:"errors,omitempty"`
}
