apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-db.name" . }}
  labels:
    {{- include "config-db.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "config-db.selectorLabels" . | nindent 4 }}
