// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ConfigAnalysis string
	ConfigChange   string
	ConfigItem     string
	ConfigScraper  string
}{
	ConfigAnalysis: "config_analysis",
	ConfigChange:   "config_change",
	ConfigItem:     "config_item",
	ConfigScraper:  "config_scraper",
}
