// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: proto/scraper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{0}
}

type PluginInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SupportedTypes []string               `protobuf:"bytes,3,rep,name=supported_types,json=supportedTypes,proto3" json:"supported_types,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_proto_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetSupportedTypes() []string {
	if x != nil {
		return x.SupportedTypes
	}
	return nil
}

type ScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScraperId     string                 `protobuf:"bytes,1,opt,name=scraper_id,json=scraperId,proto3" json:"scraper_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SpecJson      []byte                 `protobuf:"bytes,3,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"` // JSON-encoded ScraperSpec
	Incremental   bool                   `protobuf:"varint,4,opt,name=incremental,proto3" json:"incremental,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeRequest) Reset() {
	*x = ScrapeRequest{}
	mi := &file_proto_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeRequest) ProtoMessage() {}

func (x *ScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeRequest.ProtoReflect.Descriptor instead.
func (*ScrapeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *ScrapeRequest) GetScraperId() string {
	if x != nil {
		return x.ScraperId
	}
	return ""
}

func (x *ScrapeRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ScrapeRequest) GetSpecJson() []byte {
	if x != nil {
		return x.SpecJson
	}
	return nil
}

func (x *ScrapeRequest) GetIncremental() bool {
	if x != nil {
		return x.Incremental
	}
	return false
}

type ScrapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScrapeResultProto   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	mi := &file_proto_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *ScrapeResponse) GetResults() []*ScrapeResultProto {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ScrapeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CanScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecJson      []byte                 `protobuf:"bytes,1,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"` // JSON-encoded ScraperSpec
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanScrapeRequest) Reset() {
	*x = CanScrapeRequest{}
	mi := &file_proto_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanScrapeRequest) ProtoMessage() {}

func (x *CanScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanScrapeRequest.ProtoReflect.Descriptor instead.
func (*CanScrapeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *CanScrapeRequest) GetSpecJson() []byte {
	if x != nil {
		return x.SpecJson
	}
	return nil
}

type CanScrapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanScrape     bool                   `protobuf:"varint,1,opt,name=can_scrape,json=canScrape,proto3" json:"can_scrape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanScrapeResponse) Reset() {
	*x = CanScrapeResponse{}
	mi := &file_proto_scraper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanScrapeResponse) ProtoMessage() {}

func (x *CanScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanScrapeResponse.ProtoReflect.Descriptor instead.
func (*CanScrapeResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{5}
}

func (x *CanScrapeResponse) GetCanScrape() bool {
	if x != nil {
		return x.CanScrape
	}
	return false
}

type ScrapeResultProto struct {
	state              protoimpl.MessageState          `protogen:"open.v1"`
	Id                 string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConfigId           string                          `protobuf:"bytes,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Name               string                          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ConfigClass        string                          `protobuf:"bytes,4,opt,name=config_class,json=configClass,proto3" json:"config_class,omitempty"`
	ConfigType         string                          `protobuf:"bytes,5,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`
	Status             string                          `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Health             string                          `protobuf:"bytes,7,opt,name=health,proto3" json:"health,omitempty"`
	Ready              bool                            `protobuf:"varint,8,opt,name=ready,proto3" json:"ready,omitempty"`
	Description        string                          `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Aliases            []string                        `protobuf:"bytes,10,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Source             string                          `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	Config             []byte                          `protobuf:"bytes,12,opt,name=config,proto3" json:"config,omitempty"` // JSON-encoded config
	Locations          []string                        `protobuf:"bytes,13,rep,name=locations,proto3" json:"locations,omitempty"`
	Format             string                          `protobuf:"bytes,14,opt,name=format,proto3" json:"format,omitempty"`
	Icon               string                          `protobuf:"bytes,15,opt,name=icon,proto3" json:"icon,omitempty"`
	Labels             map[string]string               `protobuf:"bytes,16,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags               map[string]string               `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error              string                          `protobuf:"bytes,18,opt,name=error,proto3" json:"error,omitempty"`
	ScraperLess        bool                            `protobuf:"varint,19,opt,name=scraper_less,json=scraperLess,proto3" json:"scraper_less,omitempty"`
	CreatedAt          int64                           `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt          int64                           `protobuf:"varint,21,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	DeleteReason       string                          `protobuf:"bytes,22,opt,name=delete_reason,json=deleteReason,proto3" json:"delete_reason,omitempty"`
	Analysis           *AnalysisResultProto            `protobuf:"bytes,30,opt,name=analysis,proto3" json:"analysis,omitempty"`
	Changes            []*ChangeResultProto            `protobuf:"bytes,31,rep,name=changes,proto3" json:"changes,omitempty"`
	Relationships      []*RelationshipResultProto      `protobuf:"bytes,32,rep,name=relationships,proto3" json:"relationships,omitempty"`
	Parents            []*ConfigExternalKeyProto       `protobuf:"bytes,33,rep,name=parents,proto3" json:"parents,omitempty"`
	Children           []*ConfigExternalKeyProto       `protobuf:"bytes,34,rep,name=children,proto3" json:"children,omitempty"`
	Properties         []byte                          `protobuf:"bytes,35,opt,name=properties,proto3" json:"properties,omitempty"` // JSON-encoded properties
	ExternalRoles      []*ExternalRoleProto            `protobuf:"bytes,40,rep,name=external_roles,json=externalRoles,proto3" json:"external_roles,omitempty"`
	ExternalUsers      []*ExternalUserProto            `protobuf:"bytes,41,rep,name=external_users,json=externalUsers,proto3" json:"external_users,omitempty"`
	ExternalGroups     []*ExternalGroupProto           `protobuf:"bytes,42,rep,name=external_groups,json=externalGroups,proto3" json:"external_groups,omitempty"`
	ExternalUserGroups []*ExternalUserGroupProto       `protobuf:"bytes,43,rep,name=external_user_groups,json=externalUserGroups,proto3" json:"external_user_groups,omitempty"`
	ConfigAccess       []*ExternalConfigAccessProto    `protobuf:"bytes,44,rep,name=config_access,json=configAccess,proto3" json:"config_access,omitempty"`
	ConfigAccessLogs   []*ExternalConfigAccessLogProto `protobuf:"bytes,45,rep,name=config_access_logs,json=configAccessLogs,proto3" json:"config_access_logs,omitempty"`
	BaseScraper        []byte                          `protobuf:"bytes,50,opt,name=base_scraper,json=baseScraper,proto3" json:"base_scraper,omitempty"` // JSON-encoded BaseScraper
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScrapeResultProto) Reset() {
	*x = ScrapeResultProto{}
	mi := &file_proto_scraper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResultProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResultProto) ProtoMessage() {}

func (x *ScrapeResultProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResultProto.ProtoReflect.Descriptor instead.
func (*ScrapeResultProto) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{6}
}

func (x *ScrapeResultProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScrapeResultProto) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *ScrapeResultProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScrapeResultProto) GetConfigClass() string {
	if x != nil {
		return x.ConfigClass
	}
	return ""
}

func (x *ScrapeResultProto) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *ScrapeResultProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScrapeResultProto) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *ScrapeResultProto) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ScrapeResultProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScrapeResultProto) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *ScrapeResultProto) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ScrapeResultProto) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ScrapeResultProto) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *ScrapeResultProto) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ScrapeResultProto) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ScrapeResultProto) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ScrapeResultProto) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ScrapeResultProto) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScrapeResultProto) GetScraperLess() bool {
	if x != nil {
		return x.ScraperLess
	}
	return false
}

func (x *ScrapeResultProto) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ScrapeResultProto) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ScrapeResultProto) GetDeleteReason() string {
	if x != nil {
		return x.DeleteReason
	}
	return ""
}

func (x *ScrapeResultProto) GetAnalysis() *AnalysisResultProto {
	if x != nil {
		return x.Analysis
	}
	return nil
}

func (x *ScrapeResultProto) GetChanges() []*ChangeResultProto {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ScrapeResultProto) GetRelationships() []*RelationshipResultProto {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *ScrapeResultProto) GetParents() []*ConfigExternalKeyProto {
	if x != nil {
		return x.Parents
	}
	return nil
}

func (x *ScrapeResultProto) GetChildren() []*ConfigExternalKeyProto {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ScrapeResultProto) GetProperties() []byte {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ScrapeResultProto) GetExternalRoles() []*ExternalRoleProto {
	if x != nil {
		return x.ExternalRoles
	}
	return nil
}

func (x *ScrapeResultProto) GetExternalUsers() []*ExternalUserProto {
	if x != nil {
		return x.ExternalUsers
	}
	return nil
}

func (x *ScrapeResultProto) GetExternalGroups() []*ExternalGroupProto {
	if x != nil {
		return x.ExternalGroups
	}
	return nil
}

func (x *ScrapeResultProto) GetExternalUserGroups() []*ExternalUserGroupProto {
	if x != nil {
		return x.ExternalUserGroups
	}
	return nil
}

func (x *ScrapeResultProto) GetConfigAccess() []*ExternalConfigAccessProto {
	if x != nil {
		return x.ConfigAccess
	}
	return nil
}

func (x *ScrapeResultProto) GetConfigAccessLogs() []*ExternalConfigAccessLogProto {
	if x != nil {
		return x.ConfigAccessLogs
	}
	return nil
}

func (x *ScrapeResultProto) GetBaseScraper() []byte {
	if x != nil {
		return x.BaseScraper
	}
	return nil
}

type ConfigExternalKeyProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ScraperId     string                 `protobuf:"bytes,3,opt,name=scraper_id,json=scraperId,proto3" json:"scraper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigExternalKeyProto) Reset() {
	*x = ConfigExternalKeyProto{}
	mi := &file_proto_scraper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigExternalKeyProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigExternalKeyProto) ProtoMessage() {}

func (x *ConfigExternalKeyProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigExternalKeyProto.ProtoReflect.Descriptor instead.
func (*ConfigExternalKeyProto) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigExternalKeyProto) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ConfigExternalKeyProto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConfigExternalKeyProto) GetScraperId() string {
	if x != nil {
		return x.ScraperId
	}
	return ""
}

type AnalysisResultProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Summary         string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Analysis        []byte                 `protobuf:"bytes,2,opt,name=analysis,proto3" json:"analysis,omitempty"` // JSON-encoded map
	AnalysisType    string                 `protobuf:"bytes,3,opt,name=analysis_type,json=analysisType,proto3" json:"analysis_type,omitempty"`
	Severity        string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Source          string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Analyzer        string                 `protobuf:"bytes,6,opt,name=analyzer,proto3" json:"analyzer,omitempty"`
	Messages        []string               `protobuf:"bytes,7,rep,name=messages,proto3" json:"messages,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	FirstObserved   int64                  `protobuf:"varint,9,opt,name=first_observed,json=firstObserved,proto3" json:"first_observed,omitempty"`
	LastObserved    int64                  `protobuf:"varint,10,opt,name=last_observed,json=lastObserved,proto3" json:"last_observed,omitempty"`
	ExternalConfigs []*ExternalIDProto     `protobuf:"bytes,11,rep,name=external_configs,json=externalConfigs,proto3" json:"external_configs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalysisResultProto) Reset() {
	*x = AnalysisResultProto{}
	mi := &file_proto_scraper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResultProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResultProto) ProtoMessage() {}

func (x *AnalysisResultProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResultProto.ProtoReflect.Descriptor instead.
func (*AnalysisResultProto) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{8}
}

func (x *AnalysisResultProto) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalysisResultProto) GetAnalysis() []byte {
	if x != nil {
		return x.Analysis
	}
	return nil
}

func (x *AnalysisResultProto) GetAnalysisType() string {
	if x != nil {
		return x.AnalysisType
	}
	return ""
}

func (x *AnalysisResultProto) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AnalysisResultProto) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AnalysisResultProto) GetAnalyzer() string {
	if x != nil {
		return x.Analyzer
	}
	return ""
}

func (x *AnalysisResultProto) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *AnalysisResultProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalysisResultProto) GetFirstObserved() int64 {
	if x != nil {
		return x.FirstObserved
	}
	return 0
}

func (x *AnalysisResultProto) GetLastObserved() int64 {
	if x != nil {
		return x.LastObserved
	}
	return 0
}

func (x *AnalysisResultProto) GetExternalConfigs() []*ExternalIDProto {
	if x != nil {
		return x.ExternalConfigs
	}
	return nil
}

type ExternalIDProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	ConfigType    string                 `protobuf:"bytes,2,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`
	ScraperId     string                 `protobuf:"bytes,3,opt,name=scraper_id,json=scraperId,proto3" json:"scraper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalIDProto) Reset() {
	*x = ExternalIDProto{}
	mi := &file_proto_scraper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalIDProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalIDProto) ProtoMessage() {}

func (x *ExternalIDProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalIDProto.ProtoReflect.Descriptor instead.
func (*ExternalIDProto) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{9}
}

func (x *ExternalIDProto) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ExternalIDProto) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *ExternalIDProto) GetScraperId() string {
	if x != nil {
		return x.ScraperId
	}
	return ""
}

type ChangeResultProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ExternalId       string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	ConfigType       string                 `protobuf:"bytes,2,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`
	ScraperId        string                 `protobuf:"bytes,3,opt,name=scraper_id,json=scraperId,proto3" json:"scraper_id,omitempty"`
	ExternalChangeId string                 `protobuf:"bytes,4,opt,name=external_change_id,json=externalChangeId,proto3" json:"external_change_id,omitempty"`
	Action           string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	ChangeType       string                 `protobuf:"bytes,6,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	Patches          string                 `protobuf:"bytes,7,opt,name=patches,proto3" json:"patches,omitempty"`
	Summary          string                 `protobuf:"bytes,8,opt,name=summary,proto3" json:"summary,omitempty"`
	Severity         string                 `protobuf:"bytes,9,opt,name=severity,proto3" json:"severity,omitempty"`
	Source           string                 `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	CreatedBy        string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Details          []byte                 `protobuf:"bytes,13,opt,name=details,proto3" json:"details,omitempty"` // JSON-encoded map
	Diff             string                 `protobuf:"bytes,14,opt,name=diff,proto3" json:"diff,omitempty"`
	ConfigId         string                 `protobuf:"bytes,15,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	UpdateExisting   bool                   `protobuf:"varint,16,opt,name=update_existing,json=updateExisting,proto3" json:"update_existing,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChangeResultProto) Reset() {
	*x = ChangeResultProto{}
	mi := &file_proto_scraper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeResultProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeResultProto) ProtoMessage() {}

func (x *ChangeResultProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeResultProto.ProtoReflect.Descriptor instead.
func (*ChangeResultProto) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeResultProto) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ChangeResultProto) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *ChangeResultProto) GetScraperId() string {
	if x != nil {
		return x.ScraperId
	}
	return ""
}

func (x *ChangeResultProto) GetExternalChangeId() string {
	if x != nil {
		return x.ExternalChangeId
	}
	return ""
}

func (x *ChangeResultProto) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ChangeResultProto) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *ChangeResultProto) GetPatches() string {
	if x != nil {
		return x.Patches
	}
	return ""
}

func (x *ChangeResultProto) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ChangeResultProto) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ChangeResultProto) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ChangeResultProto) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ChangeResultProto) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ChangeResultProto) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ChangeResultProto) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *ChangeResultProto) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *ChangeResultProto) GetUpdateExisting() bool {
	if x != nil {
		return x.UpdateExisting
	}
	return false
}

type RelationshipResultProto struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfigId          string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ConfigExternalId  *ExternalIDProto       `protobuf:"bytes,2,opt,name=config_external_id,json=configExternalId,proto3" json:"config_external_id,omitempty"`
	RelatedExternalId *ExternalIDProto       `protobuf:"bytes,3,opt,name=related_external_id,json=relatedExternalId,proto3" json:"related_external_id,omitempty"`
	RelatedConfigId   string                 `protobuf:"bytes,4,opt,name=related_config_id,json=relatedConfigId,proto3" json:"related_config_id,omitempty"`
	Relationship      string                 `protobuf:"bytes,5,opt,name=relationship,proto3" json:"relationship,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RelationshipResultProto) Reset() {
	*x = RelationshipResultProto{}
	mi := &file_proto_scraper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipResultProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipResultProto) ProtoMessage() {}

func (x *RelationshipResultProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipResultProto.ProtoReflect.Descriptor instead.
func (*RelationshipResultProto) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{11}
}

func (x *RelationshipResultProto) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *RelationshipResultProto) GetConfigExternalId() *ExternalIDProto {
	if x != nil {
		return x.ConfigExternalId
	}
	return nil
}

func (x *RelationshipResultProto) GetRelatedExternalId() *ExternalIDProto {
	if x != nil {
		return x.RelatedExternalId
	}
	return nil
}

func (x *RelationshipResultProto) GetRelatedConfigId() string {
	if x != nil {
		return x.RelatedConfigId
	}
	return ""
}

func (x *RelationshipResultProto) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

type ExternalRoleProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ScraperId     string                 `protobuf:"bytes,3,opt,name=scraper_id,json=scraperId,proto3" json:"scraper_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalRoleProto) Reset() {
	*x = ExternalRoleProto{}
	mi := &file_proto_scraper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalRoleProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalRoleProto) ProtoMessage() {}

func (x *ExternalRoleProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalRoleProto.ProtoReflect.Descriptor instead.
func (*ExternalRoleProto) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{12}
}

func (x *ExternalRoleProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalRoleProto) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ExternalRoleProto) GetScraperId() string {
	if x != nil {
		return x.ScraperId
	}
	return ""
}

func (x *ExternalRoleProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExternalRoleProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ExternalUserProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ScraperId     string                 `protobuf:"bytes,3,opt,name=scraper_id,json=scraperId,proto3" json:"scraper_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,4,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserType      string                 `protobuf:"bytes,5,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalUserProto) Reset() {
	*x = ExternalUserProto{}
	mi := &file_proto_scraper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalUserProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalUserProto) ProtoMessage() {}

func (x *ExternalUserProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalUserProto.ProtoReflect.Descriptor instead.
func (*ExternalUserProto) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{13}
}

func (x *ExternalUserProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalUserProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExternalUserProto) GetScraperId() string {
	if x != nil {
		return x.ScraperId
	}
	return ""
}

func (x *ExternalUserProto) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ExternalUserProto) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *ExternalUserProto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ExternalUserProto) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ExternalUserProto) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type ExternalGroupProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ScraperId     string                 `protobuf:"bytes,3,opt,name=scraper_id,json=scraperId,proto3" json:"scraper_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	GroupType     string                 `protobuf:"bytes,5,opt,name=group_type,json=groupType,proto3" json:"group_type,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalGroupProto) Reset() {
	*x = ExternalGroupProto{}
	mi := &file_proto_scraper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalGroupProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalGroupProto) ProtoMessage() {}

func (x *ExternalGroupProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalGroupProto.ProtoReflect.Descriptor instead.
func (*ExternalGroupProto) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{14}
}

func (x *ExternalGroupProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalGroupProto) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ExternalGroupProto) GetScraperId() string {
	if x != nil {
		return x.ScraperId
	}
	return ""
}

func (x *ExternalGroupProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExternalGroupProto) GetGroupType() string {
	if x != nil {
		return x.GroupType
	}
	return ""
}

func (x *ExternalGroupProto) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ExternalGroupProto) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type ExternalUserGroupProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExternalUserId  string                 `protobuf:"bytes,1,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	ExternalGroupId string                 `protobuf:"bytes,2,opt,name=external_group_id,json=externalGroupId,proto3" json:"external_group_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExternalUserGroupProto) Reset() {
	*x = ExternalUserGroupProto{}
	mi := &file_proto_scraper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalUserGroupProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalUserGroupProto) ProtoMessage() {}

func (x *ExternalUserGroupProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalUserGroupProto.ProtoReflect.Descriptor instead.
func (*ExternalUserGroupProto) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{15}
}

func (x *ExternalUserGroupProto) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *ExternalUserGroupProto) GetExternalGroupId() string {
	if x != nil {
		return x.ExternalGroupId
	}
	return ""
}

type ExternalConfigAccessProto struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConfigId             string                 `protobuf:"bytes,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ExternalUserId       string                 `protobuf:"bytes,3,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	ExternalRoleId       string                 `protobuf:"bytes,4,opt,name=external_role_id,json=externalRoleId,proto3" json:"external_role_id,omitempty"`
	ExternalGroupId      string                 `protobuf:"bytes,5,opt,name=external_group_id,json=externalGroupId,proto3" json:"external_group_id,omitempty"`
	ScraperId            string                 `protobuf:"bytes,6,opt,name=scraper_id,json=scraperId,proto3" json:"scraper_id,omitempty"`
	CreatedAt            int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt            int64                  `protobuf:"varint,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	ConfigExternalId     *ExternalIDProto       `protobuf:"bytes,9,opt,name=config_external_id,json=configExternalId,proto3" json:"config_external_id,omitempty"`
	ExternalUserAliases  []string               `protobuf:"bytes,10,rep,name=external_user_aliases,json=externalUserAliases,proto3" json:"external_user_aliases,omitempty"`
	ExternalRoleAliases  []string               `protobuf:"bytes,11,rep,name=external_role_aliases,json=externalRoleAliases,proto3" json:"external_role_aliases,omitempty"`
	ExternalGroupAliases []string               `protobuf:"bytes,12,rep,name=external_group_aliases,json=externalGroupAliases,proto3" json:"external_group_aliases,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExternalConfigAccessProto) Reset() {
	*x = ExternalConfigAccessProto{}
	mi := &file_proto_scraper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalConfigAccessProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalConfigAccessProto) ProtoMessage() {}

func (x *ExternalConfigAccessProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalConfigAccessProto.ProtoReflect.Descriptor instead.
func (*ExternalConfigAccessProto) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{16}
}

func (x *ExternalConfigAccessProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalConfigAccessProto) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *ExternalConfigAccessProto) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *ExternalConfigAccessProto) GetExternalRoleId() string {
	if x != nil {
		return x.ExternalRoleId
	}
	return ""
}

func (x *ExternalConfigAccessProto) GetExternalGroupId() string {
	if x != nil {
		return x.ExternalGroupId
	}
	return ""
}

func (x *ExternalConfigAccessProto) GetScraperId() string {
	if x != nil {
		return x.ScraperId
	}
	return ""
}

func (x *ExternalConfigAccessProto) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ExternalConfigAccessProto) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ExternalConfigAccessProto) GetConfigExternalId() *ExternalIDProto {
	if x != nil {
		return x.ConfigExternalId
	}
	return nil
}

func (x *ExternalConfigAccessProto) GetExternalUserAliases() []string {
	if x != nil {
		return x.ExternalUserAliases
	}
	return nil
}

func (x *ExternalConfigAccessProto) GetExternalRoleAliases() []string {
	if x != nil {
		return x.ExternalRoleAliases
	}
	return nil
}

func (x *ExternalConfigAccessProto) GetExternalGroupAliases() []string {
	if x != nil {
		return x.ExternalGroupAliases
	}
	return nil
}

type ExternalConfigAccessLogProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConfigId         string                 `protobuf:"bytes,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ExternalUserId   string                 `protobuf:"bytes,3,opt,name=external_user_id,json=externalUserId,proto3" json:"external_user_id,omitempty"`
	Operation        string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	IpAddress        string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ConfigExternalId *ExternalIDProto       `protobuf:"bytes,7,opt,name=config_external_id,json=configExternalId,proto3" json:"config_external_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExternalConfigAccessLogProto) Reset() {
	*x = ExternalConfigAccessLogProto{}
	mi := &file_proto_scraper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalConfigAccessLogProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalConfigAccessLogProto) ProtoMessage() {}

func (x *ExternalConfigAccessLogProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalConfigAccessLogProto.ProtoReflect.Descriptor instead.
func (*ExternalConfigAccessLogProto) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{17}
}

func (x *ExternalConfigAccessLogProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalConfigAccessLogProto) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *ExternalConfigAccessLogProto) GetExternalUserId() string {
	if x != nil {
		return x.ExternalUserId
	}
	return ""
}

func (x *ExternalConfigAccessLogProto) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ExternalConfigAccessLogProto) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ExternalConfigAccessLogProto) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ExternalConfigAccessLogProto) GetConfigExternalId() *ExternalIDProto {
	if x != nil {
		return x.ConfigExternalId
	}
	return nil
}

// Host service messages
type ConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionRequest) Reset() {
	*x = ConnectionRequest{}
	mi := &file_proto_scraper_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionRequest) ProtoMessage() {}

func (x *ConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionRequest.ProtoReflect.Descriptor instead.
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{18}
}

func (x *ConnectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConnectionRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionResponse) Reset() {
	*x = ConnectionResponse{}
	mi := &file_proto_scraper_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionResponse) ProtoMessage() {}

func (x *ConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionResponse.ProtoReflect.Descriptor instead.
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{19}
}

func (x *ConnectionResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ConnectionResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ConnectionResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ConnectionResponse) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ConnectionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type EnvVarRequest struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Name                         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ValueFromConfigmapKeyRefName string                 `protobuf:"bytes,2,opt,name=value_from_configmap_key_ref_name,json=valueFromConfigmapKeyRefName,proto3" json:"value_from_configmap_key_ref_name,omitempty"`
	ValueFromConfigmapKeyRefKey  string                 `protobuf:"bytes,3,opt,name=value_from_configmap_key_ref_key,json=valueFromConfigmapKeyRefKey,proto3" json:"value_from_configmap_key_ref_key,omitempty"`
	ValueFromSecretKeyRefName    string                 `protobuf:"bytes,4,opt,name=value_from_secret_key_ref_name,json=valueFromSecretKeyRefName,proto3" json:"value_from_secret_key_ref_name,omitempty"`
	ValueFromSecretKeyRefKey     string                 `protobuf:"bytes,5,opt,name=value_from_secret_key_ref_key,json=valueFromSecretKeyRefKey,proto3" json:"value_from_secret_key_ref_key,omitempty"`
	ValueStatic                  string                 `protobuf:"bytes,6,opt,name=value_static,json=valueStatic,proto3" json:"value_static,omitempty"`
	Namespace                    string                 `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *EnvVarRequest) Reset() {
	*x = EnvVarRequest{}
	mi := &file_proto_scraper_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVarRequest) ProtoMessage() {}

func (x *EnvVarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVarRequest.ProtoReflect.Descriptor instead.
func (*EnvVarRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{20}
}

func (x *EnvVarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVarRequest) GetValueFromConfigmapKeyRefName() string {
	if x != nil {
		return x.ValueFromConfigmapKeyRefName
	}
	return ""
}

func (x *EnvVarRequest) GetValueFromConfigmapKeyRefKey() string {
	if x != nil {
		return x.ValueFromConfigmapKeyRefKey
	}
	return ""
}

func (x *EnvVarRequest) GetValueFromSecretKeyRefName() string {
	if x != nil {
		return x.ValueFromSecretKeyRefName
	}
	return ""
}

func (x *EnvVarRequest) GetValueFromSecretKeyRefKey() string {
	if x != nil {
		return x.ValueFromSecretKeyRefKey
	}
	return ""
}

func (x *EnvVarRequest) GetValueStatic() string {
	if x != nil {
		return x.ValueStatic
	}
	return ""
}

func (x *EnvVarRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type EnvVarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVarResponse) Reset() {
	*x = EnvVarResponse{}
	mi := &file_proto_scraper_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVarResponse) ProtoMessage() {}

func (x *EnvVarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVarResponse.ProtoReflect.Descriptor instead.
func (*EnvVarResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{21}
}

func (x *EnvVarResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EnvVarResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FindConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigType    string                 `protobuf:"bytes,1,opt,name=config_type,json=configType,proto3" json:"config_type,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	ScraperId     string                 `protobuf:"bytes,3,opt,name=scraper_id,json=scraperId,proto3" json:"scraper_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindConfigRequest) Reset() {
	*x = FindConfigRequest{}
	mi := &file_proto_scraper_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindConfigRequest) ProtoMessage() {}

func (x *FindConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindConfigRequest.ProtoReflect.Descriptor instead.
func (*FindConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{22}
}

func (x *FindConfigRequest) GetConfigType() string {
	if x != nil {
		return x.ConfigType
	}
	return ""
}

func (x *FindConfigRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *FindConfigRequest) GetScraperId() string {
	if x != nil {
		return x.ScraperId
	}
	return ""
}

type FindConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigId      string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindConfigResponse) Reset() {
	*x = FindConfigResponse{}
	mi := &file_proto_scraper_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindConfigResponse) ProtoMessage() {}

func (x *FindConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scraper_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindConfigResponse.ProtoReflect.Descriptor instead.
func (*FindConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_scraper_proto_rawDescGZIP(), []int{23}
}

func (x *FindConfigResponse) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *FindConfigResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FindConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_scraper_proto protoreflect.FileDescriptor

const file_proto_scraper_proto_rawDesc = "" +
	"\n" +
	"\x13proto/scraper.proto\x12\x0fconfigdb.plugin\"\a\n" +
	"\x05Empty\"c\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12'\n" +
	"\x0fsupported_types\x18\x03 \x03(\tR\x0esupportedTypes\"\x8b\x01\n" +
	"\rScrapeRequest\x12\x1d\n" +
	"\n" +
	"scraper_id\x18\x01 \x01(\tR\tscraperId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tspec_json\x18\x03 \x01(\fR\bspecJson\x12 \n" +
	"\vincremental\x18\x04 \x01(\bR\vincremental\"d\n" +
	"\x0eScrapeResponse\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".configdb.plugin.ScrapeResultProtoR\aresults\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"/\n" +
	"\x10CanScrapeRequest\x12\x1b\n" +
	"\tspec_json\x18\x01 \x01(\fR\bspecJson\"2\n" +
	"\x11CanScrapeResponse\x12\x1d\n" +
	"\n" +
	"can_scrape\x18\x01 \x01(\bR\tcanScrape\"\xb6\r\n" +
	"\x11ScrapeResultProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tconfig_id\x18\x02 \x01(\tR\bconfigId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fconfig_class\x18\x04 \x01(\tR\vconfigClass\x12\x1f\n" +
	"\vconfig_type\x18\x05 \x01(\tR\n" +
	"configType\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06health\x18\a \x01(\tR\x06health\x12\x14\n" +
	"\x05ready\x18\b \x01(\bR\x05ready\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x18\n" +
	"\aaliases\x18\n" +
	" \x03(\tR\aaliases\x12\x16\n" +
	"\x06source\x18\v \x01(\tR\x06source\x12\x16\n" +
	"\x06config\x18\f \x01(\fR\x06config\x12\x1c\n" +
	"\tlocations\x18\r \x03(\tR\tlocations\x12\x16\n" +
	"\x06format\x18\x0e \x01(\tR\x06format\x12\x12\n" +
	"\x04icon\x18\x0f \x01(\tR\x04icon\x12F\n" +
	"\x06labels\x18\x10 \x03(\v2..configdb.plugin.ScrapeResultProto.LabelsEntryR\x06labels\x12@\n" +
	"\x04tags\x18\x11 \x03(\v2,.configdb.plugin.ScrapeResultProto.TagsEntryR\x04tags\x12\x14\n" +
	"\x05error\x18\x12 \x01(\tR\x05error\x12!\n" +
	"\fscraper_less\x18\x13 \x01(\bR\vscraperLess\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x15 \x01(\x03R\tdeletedAt\x12#\n" +
	"\rdelete_reason\x18\x16 \x01(\tR\fdeleteReason\x12@\n" +
	"\banalysis\x18\x1e \x01(\v2$.configdb.plugin.AnalysisResultProtoR\banalysis\x12<\n" +
	"\achanges\x18\x1f \x03(\v2\".configdb.plugin.ChangeResultProtoR\achanges\x12N\n" +
	"\rrelationships\x18  \x03(\v2(.configdb.plugin.RelationshipResultProtoR\rrelationships\x12A\n" +
	"\aparents\x18! \x03(\v2'.configdb.plugin.ConfigExternalKeyProtoR\aparents\x12C\n" +
	"\bchildren\x18\" \x03(\v2'.configdb.plugin.ConfigExternalKeyProtoR\bchildren\x12\x1e\n" +
	"\n" +
	"properties\x18# \x01(\fR\n" +
	"properties\x12I\n" +
	"\x0eexternal_roles\x18( \x03(\v2\".configdb.plugin.ExternalRoleProtoR\rexternalRoles\x12I\n" +
	"\x0eexternal_users\x18) \x03(\v2\".configdb.plugin.ExternalUserProtoR\rexternalUsers\x12L\n" +
	"\x0fexternal_groups\x18* \x03(\v2#.configdb.plugin.ExternalGroupProtoR\x0eexternalGroups\x12Y\n" +
	"\x14external_user_groups\x18+ \x03(\v2'.configdb.plugin.ExternalUserGroupProtoR\x12externalUserGroups\x12O\n" +
	"\rconfig_access\x18, \x03(\v2*.configdb.plugin.ExternalConfigAccessProtoR\fconfigAccess\x12[\n" +
	"\x12config_access_logs\x18- \x03(\v2-.configdb.plugin.ExternalConfigAccessLogProtoR\x10configAccessLogs\x12!\n" +
	"\fbase_scraper\x182 \x01(\fR\vbaseScraper\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x16ConfigExternalKeyProto\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"scraper_id\x18\x03 \x01(\tR\tscraperId\"\x8d\x03\n" +
	"\x13AnalysisResultProto\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12\x1a\n" +
	"\banalysis\x18\x02 \x01(\fR\banalysis\x12#\n" +
	"\ranalysis_type\x18\x03 \x01(\tR\fanalysisType\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1a\n" +
	"\banalyzer\x18\x06 \x01(\tR\banalyzer\x12\x1a\n" +
	"\bmessages\x18\a \x03(\tR\bmessages\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12%\n" +
	"\x0efirst_observed\x18\t \x01(\x03R\rfirstObserved\x12#\n" +
	"\rlast_observed\x18\n" +
	" \x01(\x03R\flastObserved\x12K\n" +
	"\x10external_configs\x18\v \x03(\v2 .configdb.plugin.ExternalIDProtoR\x0fexternalConfigs\"r\n" +
	"\x0fExternalIDProto\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x1f\n" +
	"\vconfig_type\x18\x02 \x01(\tR\n" +
	"configType\x12\x1d\n" +
	"\n" +
	"scraper_id\x18\x03 \x01(\tR\tscraperId\"\xf5\x03\n" +
	"\x11ChangeResultProto\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x1f\n" +
	"\vconfig_type\x18\x02 \x01(\tR\n" +
	"configType\x12\x1d\n" +
	"\n" +
	"scraper_id\x18\x03 \x01(\tR\tscraperId\x12,\n" +
	"\x12external_change_id\x18\x04 \x01(\tR\x10externalChangeId\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x1f\n" +
	"\vchange_type\x18\x06 \x01(\tR\n" +
	"changeType\x12\x18\n" +
	"\apatches\x18\a \x01(\tR\apatches\x12\x18\n" +
	"\asummary\x18\b \x01(\tR\asummary\x12\x1a\n" +
	"\bseverity\x18\t \x01(\tR\bseverity\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"created_by\x18\v \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x18\n" +
	"\adetails\x18\r \x01(\fR\adetails\x12\x12\n" +
	"\x04diff\x18\x0e \x01(\tR\x04diff\x12\x1b\n" +
	"\tconfig_id\x18\x0f \x01(\tR\bconfigId\x12'\n" +
	"\x0fupdate_existing\x18\x10 \x01(\bR\x0eupdateExisting\"\xa8\x02\n" +
	"\x17RelationshipResultProto\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\x12N\n" +
	"\x12config_external_id\x18\x02 \x01(\v2 .configdb.plugin.ExternalIDProtoR\x10configExternalId\x12P\n" +
	"\x13related_external_id\x18\x03 \x01(\v2 .configdb.plugin.ExternalIDProtoR\x11relatedExternalId\x12*\n" +
	"\x11related_config_id\x18\x04 \x01(\tR\x0frelatedConfigId\x12\"\n" +
	"\frelationship\x18\x05 \x01(\tR\frelationship\"\x97\x01\n" +
	"\x11ExternalRoleProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"scraper_id\x18\x03 \x01(\tR\tscraperId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xe6\x01\n" +
	"\x11ExternalUserProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"scraper_id\x18\x03 \x01(\tR\tscraperId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x04 \x01(\tR\taccountId\x12\x1b\n" +
	"\tuser_type\x18\x05 \x01(\tR\buserType\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\b \x01(\x03R\tdeletedAt\"\xd3\x01\n" +
	"\x12ExternalGroupProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"scraper_id\x18\x03 \x01(\tR\tscraperId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"group_type\x18\x05 \x01(\tR\tgroupType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\a \x01(\x03R\tdeletedAt\"n\n" +
	"\x16ExternalUserGroupProto\x12(\n" +
	"\x10external_user_id\x18\x01 \x01(\tR\x0eexternalUserId\x12*\n" +
	"\x11external_group_id\x18\x02 \x01(\tR\x0fexternalGroupId\"\x93\x04\n" +
	"\x19ExternalConfigAccessProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tconfig_id\x18\x02 \x01(\tR\bconfigId\x12(\n" +
	"\x10external_user_id\x18\x03 \x01(\tR\x0eexternalUserId\x12(\n" +
	"\x10external_role_id\x18\x04 \x01(\tR\x0eexternalRoleId\x12*\n" +
	"\x11external_group_id\x18\x05 \x01(\tR\x0fexternalGroupId\x12\x1d\n" +
	"\n" +
	"scraper_id\x18\x06 \x01(\tR\tscraperId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\b \x01(\x03R\tdeletedAt\x12N\n" +
	"\x12config_external_id\x18\t \x01(\v2 .configdb.plugin.ExternalIDProtoR\x10configExternalId\x122\n" +
	"\x15external_user_aliases\x18\n" +
	" \x03(\tR\x13externalUserAliases\x122\n" +
	"\x15external_role_aliases\x18\v \x03(\tR\x13externalRoleAliases\x124\n" +
	"\x16external_group_aliases\x18\f \x03(\tR\x14externalGroupAliases\"\xa1\x02\n" +
	"\x1cExternalConfigAccessLogProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tconfig_id\x18\x02 \x01(\tR\bconfigId\x12(\n" +
	"\x10external_user_id\x18\x03 \x01(\tR\x0eexternalUserId\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12N\n" +
	"\x12config_external_id\x18\a \x01(\v2 .configdb.plugin.ExternalIDProtoR\x10configExternalId\"E\n" +
	"\x11ConnectionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\x88\x02\n" +
	"\x12ConnectionResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12S\n" +
	"\n" +
	"properties\x18\x04 \x03(\v23.configdb.plugin.ConnectionResponse.PropertiesEntryR\n" +
	"properties\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf8\x02\n" +
	"\rEnvVarRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12G\n" +
	"!value_from_configmap_key_ref_name\x18\x02 \x01(\tR\x1cvalueFromConfigmapKeyRefName\x12E\n" +
	" value_from_configmap_key_ref_key\x18\x03 \x01(\tR\x1bvalueFromConfigmapKeyRefKey\x12A\n" +
	"\x1evalue_from_secret_key_ref_name\x18\x04 \x01(\tR\x19valueFromSecretKeyRefName\x12?\n" +
	"\x1dvalue_from_secret_key_ref_key\x18\x05 \x01(\tR\x18valueFromSecretKeyRefKey\x12!\n" +
	"\fvalue_static\x18\x06 \x01(\tR\vvalueStatic\x12\x1c\n" +
	"\tnamespace\x18\a \x01(\tR\tnamespace\"<\n" +
	"\x0eEnvVarResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"t\n" +
	"\x11FindConfigRequest\x12\x1f\n" +
	"\vconfig_type\x18\x01 \x01(\tR\n" +
	"configType\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x1d\n" +
	"\n" +
	"scraper_id\x18\x03 \x01(\tR\tscraperId\"]\n" +
	"\x12FindConfigResponse\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xee\x01\n" +
	"\rScraperPlugin\x12I\n" +
	"\x06Scrape\x12\x1e.configdb.plugin.ScrapeRequest\x1a\x1f.configdb.plugin.ScrapeResponse\x12R\n" +
	"\tCanScrape\x12!.configdb.plugin.CanScrapeRequest\x1a\".configdb.plugin.CanScrapeResponse\x12>\n" +
	"\aGetInfo\x12\x16.configdb.plugin.Empty\x1a\x1b.configdb.plugin.PluginInfo2\x93\x02\n" +
	"\fHostServices\x12\\\n" +
	"\x11HydrateConnection\x12\".configdb.plugin.ConnectionRequest\x1a#.configdb.plugin.ConnectionResponse\x12N\n" +
	"\vGetEnvValue\x12\x1e.configdb.plugin.EnvVarRequest\x1a\x1f.configdb.plugin.EnvVarResponse\x12U\n" +
	"\n" +
	"FindConfig\x12\".configdb.plugin.FindConfigRequest\x1a#.configdb.plugin.FindConfigResponseB3Z1github.com/flanksource/config-db/api/plugin/protob\x06proto3"

var (
	file_proto_scraper_proto_rawDescOnce sync.Once
	file_proto_scraper_proto_rawDescData []byte
)

func file_proto_scraper_proto_rawDescGZIP() []byte {
	file_proto_scraper_proto_rawDescOnce.Do(func() {
		file_proto_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scraper_proto_rawDesc), len(file_proto_scraper_proto_rawDesc)))
	})
	return file_proto_scraper_proto_rawDescData
}

var file_proto_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_scraper_proto_goTypes = []any{
	(*Empty)(nil),                        // 0: configdb.plugin.Empty
	(*PluginInfo)(nil),                   // 1: configdb.plugin.PluginInfo
	(*ScrapeRequest)(nil),                // 2: configdb.plugin.ScrapeRequest
	(*ScrapeResponse)(nil),               // 3: configdb.plugin.ScrapeResponse
	(*CanScrapeRequest)(nil),             // 4: configdb.plugin.CanScrapeRequest
	(*CanScrapeResponse)(nil),            // 5: configdb.plugin.CanScrapeResponse
	(*ScrapeResultProto)(nil),            // 6: configdb.plugin.ScrapeResultProto
	(*ConfigExternalKeyProto)(nil),       // 7: configdb.plugin.ConfigExternalKeyProto
	(*AnalysisResultProto)(nil),          // 8: configdb.plugin.AnalysisResultProto
	(*ExternalIDProto)(nil),              // 9: configdb.plugin.ExternalIDProto
	(*ChangeResultProto)(nil),            // 10: configdb.plugin.ChangeResultProto
	(*RelationshipResultProto)(nil),      // 11: configdb.plugin.RelationshipResultProto
	(*ExternalRoleProto)(nil),            // 12: configdb.plugin.ExternalRoleProto
	(*ExternalUserProto)(nil),            // 13: configdb.plugin.ExternalUserProto
	(*ExternalGroupProto)(nil),           // 14: configdb.plugin.ExternalGroupProto
	(*ExternalUserGroupProto)(nil),       // 15: configdb.plugin.ExternalUserGroupProto
	(*ExternalConfigAccessProto)(nil),    // 16: configdb.plugin.ExternalConfigAccessProto
	(*ExternalConfigAccessLogProto)(nil), // 17: configdb.plugin.ExternalConfigAccessLogProto
	(*ConnectionRequest)(nil),            // 18: configdb.plugin.ConnectionRequest
	(*ConnectionResponse)(nil),           // 19: configdb.plugin.ConnectionResponse
	(*EnvVarRequest)(nil),                // 20: configdb.plugin.EnvVarRequest
	(*EnvVarResponse)(nil),               // 21: configdb.plugin.EnvVarResponse
	(*FindConfigRequest)(nil),            // 22: configdb.plugin.FindConfigRequest
	(*FindConfigResponse)(nil),           // 23: configdb.plugin.FindConfigResponse
	nil,                                  // 24: configdb.plugin.ScrapeResultProto.LabelsEntry
	nil,                                  // 25: configdb.plugin.ScrapeResultProto.TagsEntry
	nil,                                  // 26: configdb.plugin.ConnectionResponse.PropertiesEntry
}
var file_proto_scraper_proto_depIdxs = []int32{
	6,  // 0: configdb.plugin.ScrapeResponse.results:type_name -> configdb.plugin.ScrapeResultProto
	24, // 1: configdb.plugin.ScrapeResultProto.labels:type_name -> configdb.plugin.ScrapeResultProto.LabelsEntry
	25, // 2: configdb.plugin.ScrapeResultProto.tags:type_name -> configdb.plugin.ScrapeResultProto.TagsEntry
	8,  // 3: configdb.plugin.ScrapeResultProto.analysis:type_name -> configdb.plugin.AnalysisResultProto
	10, // 4: configdb.plugin.ScrapeResultProto.changes:type_name -> configdb.plugin.ChangeResultProto
	11, // 5: configdb.plugin.ScrapeResultProto.relationships:type_name -> configdb.plugin.RelationshipResultProto
	7,  // 6: configdb.plugin.ScrapeResultProto.parents:type_name -> configdb.plugin.ConfigExternalKeyProto
	7,  // 7: configdb.plugin.ScrapeResultProto.children:type_name -> configdb.plugin.ConfigExternalKeyProto
	12, // 8: configdb.plugin.ScrapeResultProto.external_roles:type_name -> configdb.plugin.ExternalRoleProto
	13, // 9: configdb.plugin.ScrapeResultProto.external_users:type_name -> configdb.plugin.ExternalUserProto
	14, // 10: configdb.plugin.ScrapeResultProto.external_groups:type_name -> configdb.plugin.ExternalGroupProto
	15, // 11: configdb.plugin.ScrapeResultProto.external_user_groups:type_name -> configdb.plugin.ExternalUserGroupProto
	16, // 12: configdb.plugin.ScrapeResultProto.config_access:type_name -> configdb.plugin.ExternalConfigAccessProto
	17, // 13: configdb.plugin.ScrapeResultProto.config_access_logs:type_name -> configdb.plugin.ExternalConfigAccessLogProto
	9,  // 14: configdb.plugin.AnalysisResultProto.external_configs:type_name -> configdb.plugin.ExternalIDProto
	9,  // 15: configdb.plugin.RelationshipResultProto.config_external_id:type_name -> configdb.plugin.ExternalIDProto
	9,  // 16: configdb.plugin.RelationshipResultProto.related_external_id:type_name -> configdb.plugin.ExternalIDProto
	9,  // 17: configdb.plugin.ExternalConfigAccessProto.config_external_id:type_name -> configdb.plugin.ExternalIDProto
	9,  // 18: configdb.plugin.ExternalConfigAccessLogProto.config_external_id:type_name -> configdb.plugin.ExternalIDProto
	26, // 19: configdb.plugin.ConnectionResponse.properties:type_name -> configdb.plugin.ConnectionResponse.PropertiesEntry
	2,  // 20: configdb.plugin.ScraperPlugin.Scrape:input_type -> configdb.plugin.ScrapeRequest
	4,  // 21: configdb.plugin.ScraperPlugin.CanScrape:input_type -> configdb.plugin.CanScrapeRequest
	0,  // 22: configdb.plugin.ScraperPlugin.GetInfo:input_type -> configdb.plugin.Empty
	18, // 23: configdb.plugin.HostServices.HydrateConnection:input_type -> configdb.plugin.ConnectionRequest
	20, // 24: configdb.plugin.HostServices.GetEnvValue:input_type -> configdb.plugin.EnvVarRequest
	22, // 25: configdb.plugin.HostServices.FindConfig:input_type -> configdb.plugin.FindConfigRequest
	3,  // 26: configdb.plugin.ScraperPlugin.Scrape:output_type -> configdb.plugin.ScrapeResponse
	5,  // 27: configdb.plugin.ScraperPlugin.CanScrape:output_type -> configdb.plugin.CanScrapeResponse
	1,  // 28: configdb.plugin.ScraperPlugin.GetInfo:output_type -> configdb.plugin.PluginInfo
	19, // 29: configdb.plugin.HostServices.HydrateConnection:output_type -> configdb.plugin.ConnectionResponse
	21, // 30: configdb.plugin.HostServices.GetEnvValue:output_type -> configdb.plugin.EnvVarResponse
	23, // 31: configdb.plugin.HostServices.FindConfig:output_type -> configdb.plugin.FindConfigResponse
	26, // [26:32] is the sub-list for method output_type
	20, // [20:26] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_scraper_proto_init() }
func file_proto_scraper_proto_init() {
	if File_proto_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scraper_proto_rawDesc), len(file_proto_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_scraper_proto_goTypes,
		DependencyIndexes: file_proto_scraper_proto_depIdxs,
		MessageInfos:      file_proto_scraper_proto_msgTypes,
	}.Build()
	File_proto_scraper_proto = out.File
	file_proto_scraper_proto_goTypes = nil
	file_proto_scraper_proto_depIdxs = nil
}
