// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.9
// source: proto/scraper.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScraperPlugin_Scrape_FullMethodName    = "/configdb.plugin.ScraperPlugin/Scrape"
	ScraperPlugin_CanScrape_FullMethodName = "/configdb.plugin.ScraperPlugin/CanScrape"
	ScraperPlugin_GetInfo_FullMethodName   = "/configdb.plugin.ScraperPlugin/GetInfo"
)

// ScraperPluginClient is the client API for ScraperPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScraperPlugin is implemented by plugins (called by host)
type ScraperPluginClient interface {
	Scrape(ctx context.Context, in *ScrapeRequest, opts ...grpc.CallOption) (*ScrapeResponse, error)
	CanScrape(ctx context.Context, in *CanScrapeRequest, opts ...grpc.CallOption) (*CanScrapeResponse, error)
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
}

type scraperPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewScraperPluginClient(cc grpc.ClientConnInterface) ScraperPluginClient {
	return &scraperPluginClient{cc}
}

func (c *scraperPluginClient) Scrape(ctx context.Context, in *ScrapeRequest, opts ...grpc.CallOption) (*ScrapeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScrapeResponse)
	err := c.cc.Invoke(ctx, ScraperPlugin_Scrape_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperPluginClient) CanScrape(ctx context.Context, in *CanScrapeRequest, opts ...grpc.CallOption) (*CanScrapeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanScrapeResponse)
	err := c.cc.Invoke(ctx, ScraperPlugin_CanScrape_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scraperPluginClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, ScraperPlugin_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScraperPluginServer is the server API for ScraperPlugin service.
// All implementations must embed UnimplementedScraperPluginServer
// for forward compatibility.
//
// ScraperPlugin is implemented by plugins (called by host)
type ScraperPluginServer interface {
	Scrape(context.Context, *ScrapeRequest) (*ScrapeResponse, error)
	CanScrape(context.Context, *CanScrapeRequest) (*CanScrapeResponse, error)
	GetInfo(context.Context, *Empty) (*PluginInfo, error)
	mustEmbedUnimplementedScraperPluginServer()
}

// UnimplementedScraperPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScraperPluginServer struct{}

func (UnimplementedScraperPluginServer) Scrape(context.Context, *ScrapeRequest) (*ScrapeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scrape not implemented")
}
func (UnimplementedScraperPluginServer) CanScrape(context.Context, *CanScrapeRequest) (*CanScrapeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanScrape not implemented")
}
func (UnimplementedScraperPluginServer) GetInfo(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedScraperPluginServer) mustEmbedUnimplementedScraperPluginServer() {}
func (UnimplementedScraperPluginServer) testEmbeddedByValue()                       {}

// UnsafeScraperPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScraperPluginServer will
// result in compilation errors.
type UnsafeScraperPluginServer interface {
	mustEmbedUnimplementedScraperPluginServer()
}

func RegisterScraperPluginServer(s grpc.ServiceRegistrar, srv ScraperPluginServer) {
	// If the following call panics, it indicates UnimplementedScraperPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScraperPlugin_ServiceDesc, srv)
}

func _ScraperPlugin_Scrape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperPluginServer).Scrape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperPlugin_Scrape_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperPluginServer).Scrape(ctx, req.(*ScrapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperPlugin_CanScrape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanScrapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperPluginServer).CanScrape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperPlugin_CanScrape_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperPluginServer).CanScrape(ctx, req.(*CanScrapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScraperPlugin_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperPluginServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperPlugin_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperPluginServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ScraperPlugin_ServiceDesc is the grpc.ServiceDesc for ScraperPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScraperPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configdb.plugin.ScraperPlugin",
	HandlerType: (*ScraperPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scrape",
			Handler:    _ScraperPlugin_Scrape_Handler,
		},
		{
			MethodName: "CanScrape",
			Handler:    _ScraperPlugin_CanScrape_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _ScraperPlugin_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scraper.proto",
}

const (
	HostServices_HydrateConnection_FullMethodName = "/configdb.plugin.HostServices/HydrateConnection"
	HostServices_GetEnvValue_FullMethodName       = "/configdb.plugin.HostServices/GetEnvValue"
	HostServices_FindConfig_FullMethodName        = "/configdb.plugin.HostServices/FindConfig"
)

// HostServicesClient is the client API for HostServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostServices is implemented by host (called by plugin)
type HostServicesClient interface {
	HydrateConnection(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error)
	GetEnvValue(ctx context.Context, in *EnvVarRequest, opts ...grpc.CallOption) (*EnvVarResponse, error)
	FindConfig(ctx context.Context, in *FindConfigRequest, opts ...grpc.CallOption) (*FindConfigResponse, error)
}

type hostServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServicesClient(cc grpc.ClientConnInterface) HostServicesClient {
	return &hostServicesClient{cc}
}

func (c *hostServicesClient) HydrateConnection(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionResponse)
	err := c.cc.Invoke(ctx, HostServices_HydrateConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) GetEnvValue(ctx context.Context, in *EnvVarRequest, opts ...grpc.CallOption) (*EnvVarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvVarResponse)
	err := c.cc.Invoke(ctx, HostServices_GetEnvValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServicesClient) FindConfig(ctx context.Context, in *FindConfigRequest, opts ...grpc.CallOption) (*FindConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindConfigResponse)
	err := c.cc.Invoke(ctx, HostServices_FindConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServicesServer is the server API for HostServices service.
// All implementations must embed UnimplementedHostServicesServer
// for forward compatibility.
//
// HostServices is implemented by host (called by plugin)
type HostServicesServer interface {
	HydrateConnection(context.Context, *ConnectionRequest) (*ConnectionResponse, error)
	GetEnvValue(context.Context, *EnvVarRequest) (*EnvVarResponse, error)
	FindConfig(context.Context, *FindConfigRequest) (*FindConfigResponse, error)
	mustEmbedUnimplementedHostServicesServer()
}

// UnimplementedHostServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServicesServer struct{}

func (UnimplementedHostServicesServer) HydrateConnection(context.Context, *ConnectionRequest) (*ConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HydrateConnection not implemented")
}
func (UnimplementedHostServicesServer) GetEnvValue(context.Context, *EnvVarRequest) (*EnvVarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnvValue not implemented")
}
func (UnimplementedHostServicesServer) FindConfig(context.Context, *FindConfigRequest) (*FindConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindConfig not implemented")
}
func (UnimplementedHostServicesServer) mustEmbedUnimplementedHostServicesServer() {}
func (UnimplementedHostServicesServer) testEmbeddedByValue()                      {}

// UnsafeHostServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServicesServer will
// result in compilation errors.
type UnsafeHostServicesServer interface {
	mustEmbedUnimplementedHostServicesServer()
}

func RegisterHostServicesServer(s grpc.ServiceRegistrar, srv HostServicesServer) {
	// If the following call panics, it indicates UnimplementedHostServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostServices_ServiceDesc, srv)
}

func _HostServices_HydrateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).HydrateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_HydrateConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).HydrateConnection(ctx, req.(*ConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_GetEnvValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvVarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).GetEnvValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_GetEnvValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).GetEnvValue(ctx, req.(*EnvVarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostServices_FindConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServicesServer).FindConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostServices_FindConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServicesServer).FindConfig(ctx, req.(*FindConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostServices_ServiceDesc is the grpc.ServiceDesc for HostServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "configdb.plugin.HostServices",
	HandlerType: (*HostServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HydrateConnection",
			Handler:    _HostServices_HydrateConnection_Handler,
		},
		{
			MethodName: "GetEnvValue",
			Handler:    _HostServices_GetEnvValue_Handler,
		},
		{
			MethodName: "FindConfig",
			Handler:    _HostServices_FindConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scraper.proto",
}
