---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - configs.flanksource.com
  resources:
  - scrapeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configs.flanksource.com
  resources:
  - scrapeconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - configs.flanksource.com
  resources:
  - scrapeconfigs/status
  verbs:
  - get
  - patch
  - update
