# permissions for end users to view scrapers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scraper-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: scraper-viewer-role
rules:
- apiGroups:
  - configs.flanksource.com
  resources:
  - scrapers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configs.flanksource.com
  resources:
  - scrapers/status
  verbs:
  - get
